package com.privacity.common.enumeration;

public enum ProtocoloActionsEnum {

	//PROTOCOLO_COMPONENT_REQUEST_ID("//PROTOCOLO_COMPONENT_REQUEST_ID"),
	/*"olds"*/
	//PROTOCOLO_COMPONENT_AUTH("//PROTOCOLO_COMPONENT_AUTH"),
	//PROTOCOLO_COMPONENT_ENCRYPT_KEYS("//PROTOCOLO_COMPONENT_ENCRYPT_KEYS"),
	//PROTOCOLO_COMPONENT_GRUPO("//PROTOCOLO_COMPONENT_GRUPO"),
	//PROTOCOLO_COMPONENT_MESSAGE("//PROTOCOLO_COMPONENT_MESSAGE"),
	//PROTOCOLO_COMPONENT_MY_ACCOUNT("//PROTOCOLO_COMPONENT_MY_ACCOUNT"),
	//PROTOCOLO_COMPONENT_PRIVACITY_RSA("//PROTOCOLO_COMPONENT_PRIVACITY_RSA"),
	//PROTOCOLO_COMPONENT_SERVER_CONF_UNSECURE("//PROTOCOLO_COMPONENT_SERVER_CONF_UNSECURE"),
	GRUPO_ACCEPT_INVITATION("GRUPO_ACCEPT_INVITATION"),
	GRUPO_DELETE("GRUPO_DELETE"),
	GRUPO_GRAL_CONF_SAVE_LOCK("GRUPO_GRAL_CONF_SAVE_LOCK"),
	GRUPO_LIST_MEMBERS("GRUPO_LIST_MEMBERS"),
	GRUPO_LOGIN("GRUPO_LOGIN"),
	GRUPO_NEW_GRUPO("GRUPO_NEW_GRUPO"),
	GRUPO_REMOVE_ME("GRUPO_REMOVE_ME"),
	GRUPO_SAVE_GRUPO_USER_CONF("GRUPO_SAVE_GRUPO_USER_CONF"),
	GRUPO_SENT_INVITATION("GRUPO_SENT_INVITATION"),
	MESSAGE_DELETE_FOR_ME("MESSAGE_DELETE_FOR_ME"),
	MESSAGE_EMPTY_LIST("MESSAGE_EMPTY_LIST"),
	MESSAGE_GET_MEDIA_1("MESSAGE_GET_MEDIA_1"),
	MESSAGE_GET_MEDIA_2("MESSAGE_GET_MEDIA_2"),
	MESSAGE_GET_ID_HISTORIAL("MESSAGE_GET_ID_HISTORIAL"),
	MESSAGE_GET_LOAD_MESSAGES("MESSAGE_GET_LOAD_MESSAGES"),
	MY_ACCOUNT_INVITATION_CODE_GENERATOR("MY_ACCOUNT_INVITATION_CODE_GENERATOR"),
	MY_ACCOUNT_IS_INVITATION_CODE_AVAILABLE("MY_ACCOUNT_IS_INVITATION_CODE_AVAILABLE"),
	MY_ACCOUNT_SAVE_CODE_AVAILABLE("MY_ACCOUNT_SAVE_CODE_AVAILABLE"),
	MY_ACCOUNT_SAVE_LOCK("MY_ACCOUNT_SAVE_LOCK"),
	MY_ACCOUNT_SAVE_NICKNAME("MY_ACCOUNT_SAVE_NICKNAME"),
	MY_ACCOUNT_SAVE_PASSWORD("MY_ACCOUNT_SAVE_PASSWORD"),
	PING_ACTION("PING ACTION"),
	PROTOCOLO_ACTION_AUTH_LOGIN("PROTOCOLO_ACTION_AUTH_LOGIN"),
	PROTOCOLO_ACTION_AUTH_REGISTER("PROTOCOLO_ACTION_AUTH_REGISTER"),
	PROTOCOLO_ACTION_AUTH_VALIDATE_USERNAME("PROTOCOLO_ACTION_AUTH_VALIDATE_USERNAME"),
	PROTOCOLO_ACTION_ENCRYPT_KEYS_CREATE("PROTOCOLO_ACTION_ENCRYPT_KEYS_CREATE"),
	PROTOCOLO_ACTION_ENCRYPT_KEYS_GET("PROTOCOLO_ACTION_ENCRYPT_KEYS_GET"),
	PROTOCOLO_ACTION_GRUPO_ADDUSER_ADDME("PROTOCOLO_ACTION_GRUPO_ADDUSER_ADDME"),
	PROTOCOLO_ACTION_GRUPO_BLOCK_REMOTO("PROTOCOLO_ACTION_GRUPO_BLOCK_REMOTO"),
	PROTOCOLO_ACTION_GRUPO_GET_GRUPO_BY_ID("PROTOCOLO_ACTION_GRUPO_GET_GRUPO_BY_ID"),
	PROTOCOLO_ACTION_GRUPO_GET_GRUPO_BY_IDS("PROTOCOLO_ACTION_GRUPO_GET_GRUPO_BY_IDS"),
	PROTOCOLO_ACTION_GRUPO_GET_IDS_MY_GRUPOS("PROTOCOLO_ACTION_GRUPO_GET_IDS_MY_GRUPOS"),
	PROTOCOLO_ACTION_GRUPO_HOW_MANY_MEMBERS_ONLINE("PROTOCOLO_ACTION_GRUPO_HOW_MANY_MEMBERS_ONLINE"),
	PROTOCOLO_ACTION_GRUPO_INVITATION_RECIVED("PROTOCOLO_ACTION_GRUPO_INVITATION_RECIVED"),
	PROTOCOLO_ACTION_GRUPO_LIST_MY_GRUPOS("PROTOCOLO_ACTION_GRUPO_LIST_MY_GRUPOS"),
	PROTOCOLO_ACTION_GRUPO_NEW_GRUPO("PROTOCOLO_ACTION_GRUPO_NEW_GRUPO"),
	PROTOCOLO_ACTION_GRUPO_REMOVE_USER("PROTOCOLO_ACTION_GRUPO_REMOVE_USER"),
	PROTOCOLO_ACTION_GRUPO_SAVE_GENERAL_CONFIGURATION("PROTOCOLO_ACTION_GRUPO_SAVE_GENERAL_CONFIGURATION"),
	PROTOCOLO_ACTION_GRUPO_SAVE_GENERAL_CONFIGURATION_LOCK("PROTOCOLO_ACTION_GRUPO_SAVE_GENERAL_CONFIGURATION_LOCK"),
	PROTOCOLO_ACTION_GRUPO_SAVE_GRAL_CONF_PASSWORD("PROTOCOLO_ACTION_GRUPO_SAVE_GRAL_CONF_PASSWORD"),
	PROTOCOLO_ACTION_GRUPO_SAVE_NICKNAME("PROTOCOLO_ACTION_GRUPO_SAVE_NICKNAME"),
	PROTOCOLO_ACTION_GRUPO_STOP_WRITTING("PROTOCOLO_ACTION_GRUPO_STOP_WRITTING"),
	PROTOCOLO_ACTION_GRUPO_UPDATE_GRUPO("PROTOCOLO_ACTION_GRUPO_UPDATE_GRUPO"),
	PROTOCOLO_ACTION_GRUPO_WRITTING("PROTOCOLO_ACTION_GRUPO_WRITTING"),
	PROTOCOLO_ACTION_MESSAGE_CHANGE_STATE("PROTOCOLO_ACTION_MESSAGE_CHANGE_STATE"),
	PROTOCOLO_ACTION_MESSAGE_DELETE_FOR_EVERYONE("PROTOCOLO_ACTION_MESSAGE_DELETE_FOR_EVERYONE"),
	PROTOCOLO_ACTION_MESSAGE_GET_ALL_ID_MESSAGE_UNREAD("PROTOCOLO_ACTION_MESSAGE_GET_ALL_ID_MESSAGE_UNREAD"),
	PROTOCOLO_ACTION_MESSAGE_GET_MESSAGE("PROTOCOLO_ACTION_MESSAGE_GET_MESSAGE"),
	PROTOCOLO_ACTION_MESSAGE_RECIVIED("PROTOCOLO_ACTION_MESSAGE_RECIVIED"),
	PROTOCOLO_ACTION_MESSAGE_SEND("PROTOCOLO_ACTION_MESSAGE_SEND"),
	PROTOCOLO_ACTION_MY_ACCOUNT_CLOSE_SESSION("PROTOCOLO_ACTION_MY_ACCOUNT_CLOSE_SESSION"),
	PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_GENERAL_CONFIGURATION("PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_GENERAL_CONFIGURATION"),
	PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_LOCK("PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_LOCK"),
	PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_LOGIN_SKIP("PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_LOGIN_SKIP"),
	PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_NICKNAME("PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_NICKNAME"),
	PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_PASSWORD("PROTOCOLO_ACTION_MY_ACCOUNT_SAVE_PASSWORD"),
	PROTOCOLO_ACTION_PRIVACITY_RSA_GET_PUBLIC_KEY("PROTOCOLO_ACTION_PRIVACITY_RSA_GET_PUBLIC_KEY"),
	PROTOCOLO_ACTION_REQUEST_ID_PRIVATE_GET("PROTOCOLO_ACTION_REQUEST_ID_PRIVATE_GET"),
	PROTOCOLO_ACTION_REQUEST_ID_PUBLIC_GET("PROTOCOLO_ACTION_REQUEST_ID_PUBLIC_GET"),
	PROTOCOLO_ACTION_SERVER_CONF_UNSECURE_GET_GRAL_CONF("PROTOCOLO_ACTION_SERVER_CONF_UNSECURE_GET_GRAL_CONF"),
	PROTOCOLO_ACTION_SERVER_CONF_UNSECURE_GET_TIME("PROTOCOLO_ACTION_SERVER_CONF_UNSECURE_GET_TIME");





	
	private final String name;       

	private ProtocoloActionsEnum(String s) {
		name = s;
	}

	public boolean equalsName(String otherName) {
		// (otherName == null) check is not needed because name.equals(null) returns false 
		return name.equals(otherName);
	}

	public String toString() {
		return this.name;
	}
}
