package com.privacity.common.util;

import java.io.StringReader;

import com.privacity.common.model.Placeholder;
import com.privacity.common.model.Root;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.Unmarshaller;

public class CreateStringXML {


	public static void main(String[] args) throws Exception {

	    String xmlString = "<resources>              <string name=\"general__inform__problem\">Si el problema persiste informelo</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__on\">Activado</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__off\">Apagado</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__null\">Sin Configurar</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__allow\">Permitido</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__block\">Bloqueado</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__mandatory\">Obligatorio</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_help__common__messaging__reconnect\">frame_help__common__messaging__reconnect</string>\r\n"
	    		+ "    <string name=\"frame_help__frame_my_account__lock\">frame_help__frame_my_account__lock</string>\r\n"
	    		+ "    <string name=\"frame_help__frame_my_account_login_skip_help_include\">El vocablo latino paragraphus se transformó en párrafo, un término de uso habitual en el ámbito de la gramática. Se trata de los diferentes fragmentos de un texto, que pueden reconocerse por su mayúscula al comenzar y por el punto y aparte que marca su final.\\r\\n \\r\\n Un párrafo puede estar formado por una o más oraciones. Cada una de ellas se encuentra separada de la otra a través de un punto y seguido. Las oraciones, a su vez, son conjuntos de palabras que componen una unidad de sentido. Si seguimos desmenuzando los elementos, también podemos afirmar que las palabras se crean a partir de la combinación de letras.</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__my_message_error_not_send\">item_list_view_message_detail__state__my_message_error_not_send</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__message_sent\">item_list_view_message_detail__state__message_sent</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__message_sending\">item_list_view_message_detail__state__message_sending</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_server\">item_list_view_message_detail__state__destiny_server</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_delivered\">item_list_view_message_detail__state__destiny_delivered</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_read_hidden\">item_list_view_message_detail__state__destiny_read_hidden</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_read\">item_list_view_message_detail__state__destiny_read</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__anonimo\">Es un mensaje con envío Anónimo</string>\r\n"
	    		+ "    <string name=\"message_detail__icon__block_download\">Descarga Bloqueada</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__random_nickname\">message_detail__icon__random_nickname</string>\r\n"
	    		+ "    <string name=\"message_detail__icon__is_audio_message\">Es un mensaje de audio</string>\r\n"
	    		+ "    <string name=\"message_detail__icon__is_hide_message_read_state\">message_detail__icon__is_hide_message_read_state</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_time\">Es un mensaje Temporal</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__has_image\">Contiene una Imagen</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_resend\">Es un mensaje Reenviado</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_reply\">Es una respuesta a otro mensaje</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_extra_encrypt\">Tiene Extra Encriptación</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__block_resend_true\">Mensaje con Bloqueo de Reenvío</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_black\">Es un mensaje en Modo Black</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__block_resend_false\">Mensaje sin Bloqueo de Reenvío</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__allow_audio_txt\">Bloquear mensajes de Audio</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_text_resize__max_size\">Tamaño máximo</string>\r\n"
	    		+ "    <string name=\"frame_text_resize__min_size\">Tamaño mínimo</string>\r\n"
	    		+ "    <string name=\"general__password\">Contraseña</string>\r\n"
	    		+ "    <string name=\"general__role\">Rol</string>\r\n"
	    		+ "    <string name=\"menu_message__empty_list\">Vaciar Mensajes</string>\r\n"
	    		+ "    <string name=\"menu_message__get_historial\">Cargar 10 Mensajes Anteriores</string>\r\n"
	    		+ "    <string name=\"menu_message__add_member\">Agregar Contacto al Grupo</string>\r\n"
	    		+ "    <string name=\"menu_message__grupo_info\">Información del Grupo</string>\r\n"
	    		+ "    <string name=\"general__actual_password\">Actual contraseña</string>\r\n"
	    		+ "    <string name=\"general__new_password\"> </string>\r\n"
	    		+ "    <string name=\"general__password_confirmar\">Confirmación</string>\r\n"
	    		+ "    <string name=\"general__save\">Guardar</string>\r\n"
	    		+ "    <string name=\"general__save_close\">Guardar y Cerrar</string>\r\n"
	    		+ "    <string name=\"general__confirm\">Confirmar</string>\r\n"
	    		+ "    <string name=\"general__are_u_sure\">¿Estás Seguro?</string>\r\n"
	    		+ "    <string name=\"general__cancel\">Cancelar</string>\r\n"
	    		+ "    <string name=\"general__accept\">Aceptar</string>\r\n"
	    		+ "    <string name=\"general__example\">Example Exemple Ejemplo Exemplo приклад</string>\r\n"
	    		+ "    <string name=\"general__log\">Detalles</string>\r\n"
	    		+ "    <string name=\"general__reset\">Reestablecer</string>\r\n"
	    		+ "    <string name=\"general__ignore\">Ignorar</string>\r\n"
	    		+ "    <string name=\"general__saved\">Guardado</string>\r\n"
	    		+ "    <string name=\"general__share\">Compartir</string>\r\n"
	    		+ "    <string name=\"general__available\">Disponible</string>\r\n"
	    		+ "    <string name=\"general__not_available\">No disponible</string>\r\n"
	    		+ "    <string name=\"general__recomendado\">Recomendado</string>\r\n"
	    		+ "    <string name=\"general__default\">Reestablecer</string>\r\n"
	    		+ "    <string name=\"general__error_ph1\">Error: %1$s</string>\r\n"
	    		+ "    <string name=\"general__error__no_description\">código: %1$s - sin descripción</string>\r\n"
	    		+ "    <string name=\"general__error_message\">Mensaje de Error</string>\r\n"
	    		+ "    <string name=\"general__error_message_ph1\">Mensaje de Error: %1$s</string>\r\n"
	    		+ "    <string name=\"general__error__call_rest__title\">Error llamando al Servidor: %1$s</string>\r\n"
	    		+ "    <string name=\"general__roles__admin\">Administrador</string>\r\n"
	    		+ "    <string name=\"general__roles__moderator\">Moderador</string>\r\n"
	    		+ "    <string name=\"general__save__not_changes\">No hay modificaciones que guardar</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lang__title\">Idioma y Visualización</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"general__roles__member\">Miembro</string>\r\n"
	    		+ "    <string name=\"general__roles__readonly\">Solo Lectura</string>\r\n"
	    		+ "    <string name=\"general__message_type__anonimous\">Anónimo</string>\r\n"
	    		+ "    <string name=\"general__message_type__temporal\">Temporal</string>\r\n"
	    		+ "    <string name=\"general__message_type__black\">Black</string>\r\n"
	    		+ "    <string name=\"general__message_type__extra_encriptado\">Extra Encriptado</string>\r\n"
	    		+ "    <string name=\"general__alert__validation__password_incorrect\">Contraseña Incorrecto</string>\r\n"
	    		+ "    <string name=\"general__alert__validation__role__only_admin\">Esta pantalla es solo para Administradores. Su rol es %1$s</string>\r\n"
	    		+ "    <string name=\"general__message_status__my_message_error_not_send\">Error</string>\r\n"
	    		+ "    <string name=\"general__message_status__my_message_sending\">Enviando</string>\r\n"
	    		+ "    <string name=\"general__message_status__my_message_sent\">Enviado</string>\r\n"
	    		+ "    <string name=\"general__message_status__destiny_server\">Servidor</string>\r\n"
	    		+ "    <string name=\"general__message_status__destiny_delivered\">Entregado</string>\r\n"
	    		+ "    <string name=\"general__message_status__destiny_readed\">Leído</string>\r\n"
	    		+ "    <string name=\"dialog_to_show__alert__validation_by_role\">Acción no permitida. Su rol en el grupo es %1$s</string>\r\n"
	    		+ "    <string name=\"copy_paste_util__no_data_to_copy\">No hay datos que copiar</string>\r\n"
	    		+ "    <string name=\"copy_paste_util__copied\">Copiado</string>\r\n"
	    		+ "    <string name=\"copy_paste_util__copy\">Copiar</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__create_grupo\">Crear Grupo</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__invitation_code\">Código de Invitación</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__my_account\">Mi cuenta</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__about_this\">Acerca de</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__exit\">Salir</string>\r\n"
	    		+ "    <string name=\"accept_invitation_callrest__invitation_accepted\">Invitación Aceptada</string>\r\n"
	    		+ "    <string name=\"grupo_info_activity__title\">Información Grupo: %1$s</string>\r\n"
	    		+ "    <string name=\"grupo_info_activity__remove_me__success\">Has dejado el grupo</string>\r\n"
	    		+ "    <string name=\"grupo_info_activity__delete_grupo__success\">Grupo eliminado</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__bloqueo_remoto__title\">Bloque Remoto</string>\r\n"
	    		+ "    <string name=\"general__enter_password__for_action\">Ingrese su contraseña para realizar esta acción</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__members__title\">Integrantes</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__members__add_member\">Agregar nuevo Integrante</string>\r\n"
	    		+ "    <string name=\"message_activity__envio_especial__title\">Envío Especial</string>\r\n"
	    		+ "    <string name=\"message_activity__delete_message__for_me\">Eliminar para Mi</string>\r\n"
	    		+ "    <string name=\"message_activity__delete_message__for_everyone\">Eliminar para todos</string>\r\n"
	    		+ "    <string name=\"message_activity__delete_message__for_everyone_and_resend\">Eliminar para todos y reenvíos</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__delete\">Eliminar</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__forward\">Reenviar</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__response\">Responder</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__reintentar\">Reintentar</string>\r\n"
	    		+ "    <string name=\"message_activity_audio__error__init\">No se pudo inicializar AudioTrack, verifique la configuración</string>\r\n"
	    		+ "    <string name=\"message_activity__extra_encrypt__delete__question\">¿Desea Borrar la Extra Encrypt Key?</string>\r\n"
	    		+ "    <string name=\"message_activity__extra_encrypt__add_key\">Ingrese Extra Encrypt Key</string>\r\n"
	    		+ "    <string name=\"message_resend_activity__title\">Reenviar</string>\r\n"
	    		+ "    <string name=\"message_resend_activity__resend__sucess\">Mensaje/s Reenviado</string>\r\n"
	    		+ "    <string name=\"message_resend_activity__resend__fail\">Error al Reenviar</string>\r\n"
	    		+ "    <string name=\"main_login__registrarse\">Registrarse</string>\r\n"
	    		+ "    <string name=\"main_login__ingresar\">Ingresar</string>\r\n"
	    		+ "    <string name=\"main_login__usuario\">Usuario</string>\r\n"
	    		+ "    <string name=\"main_login__password\">Contraseña</string>\r\n"
	    		+ "    <string name=\"main_login__alert__sin_internet__title\">Sin Internet</string>\r\n"
	    		+ "    <string name=\"main_login__alert__sin_internet__detail\">Verifique su conexión a internet.</string>\r\n"
	    		+ "    <string name=\"main_login__validate_password__empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"main_login__validate_usuario__empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"main_login__title\">Privacity</string>\r\n"
	    		+ "    <string name=\"main_login__alert__servidor_no_responde__title\">El servidor configurado no responde</string>\r\n"
	    		+ "    <string name=\"main_login__alert__servidor_no_responde___detail\">Verifique la configuración</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"main_login__alert__alert__error_rest__title\">ERROR</string>\r\n"
	    		+ "    <string name=\"main_login__alert__alert__error_rest__detail\">Ejecutando Rest: %1$s</string>\r\n"
	    		+ "    <string name=\"main_login__menu__item__configuration\">Configuración</string>\r\n"
	    		+ "    <string name=\"main_login__menu__item__espanol\">Español</string>\r\n"
	    		+ "    <string name=\"main_login__menu__item__english\">English</string>\r\n"
	    		+ "    <string name=\"main_login__version\">Versión %1$s</string>\r\n"
	    		+ "    <string name=\"lock_activity__bloqueo_remoto_mensaje\">Algún grupo ha enviado un bloqueo remoto</string>\r\n"
	    		+ "    <string name=\"register_activity__usuario\">Usuario</string>\r\n"
	    		+ "    <string name=\"register_activity__password\">Contraseña</string>\r\n"
	    		+ "    <string name=\"register_activity__password_confirmar\">Confirmar</string>\r\n"
	    		+ "    <string name=\"register_activity__requerido\">* Requerido</string>\r\n"
	    		+ "    <string name=\"register_activity__submit\">CREAR CUENTA</string>\r\n"
	    		+ "    <string name=\"register_activity__submit__procesando\">Procesando</string>\r\n"
	    		+ "    <string name=\"registro_title\">Registración</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_empty\">El usuario no puede estar vacío</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_too_short\">El usuario debe tener al menos %1$ caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_too_long\">El usuario debe tener máximo %1$ caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_nickname_empty\">El nickname no puede estar vacío</string>\r\n"
	    		+ "    <string name=\"registro_validation_nickname_too_long\">El nickname debe tener máximo %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_exists\">El nombre de usuario ya está utilizado</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_ok\">El nombre de usuario es válido</string>\r\n"
	    		+ "    <string name=\"registro_validation_error\">Hay error/es en la validación</string>\r\n"
	    		+ "    <string name=\"registro_validation_password2_no_change\">Debe ser diferente al actual</string>\r\n"
	    		+ "    <string name=\"registro_validation_password2\">Las contraseñas son diferentes</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_too_short\">Debe tener al menos %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_too_short\">Podría tener al menos %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_too_long\">Debe tener al máximo %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_white_space\">No puede contener espacios en blanco</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_contains_white_space\">Podría no contener espacios en blanco</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_special\">Debe tener al menos %1$s carácter especial</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_specials\">Debe tener al menos %1$s caracteres especiales</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_special\">Tener al menos %1$s carácter especial</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_specials\">Tener al menos %1$s caracteres especiales</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia\">Sugerencia:</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_muy_seguro\">Muy Seguro</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_mayuscula\">Debe tener al menos %1$s mayúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_mayusculas\">Debe tener al menos %1$s mayúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_mayuscula\">Tener al menos %1$s mayúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_mayusculas\">Tener al menos %1$s mayúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_minuscula\">Debe tener al menos %1$s minúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_minusculas\">Debe tener al menos %1$s minúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_minuscula\">Tener al menos %1$s minúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_minusculas\">Tener al menos %1$s minúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_numero\">Debe tener al menos %1$s número</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_numeros\">Debe tener al menos %1$s números</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_numero\">Tener al menos %1$s número</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_numeros\">Tener al menos %1$s números</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_ilegal_match\">No puede tener %1$s caracteres consecutivos</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_sugerencia_ilegal_match\">Podría no tener %1$s caracteres consecutivos</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_usuario\">El usuario no puede estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_sugerencia_usuario\">El usuario podría no estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_nickname\">El nickname no puede estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_sugerencia_nickname\">El nickname podría no estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_password\">La contraseña no puede estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_sugerencia_password\">La contraseña podría no estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_ok\">La contraseña es válida</string>\r\n"
	    		+ "    <string name=\"registro_validation_password2_ok\">Las contraseñas son correctas</string>\r\n"
	    		+ "    <string name=\"registro_nickname_notification\">Si se deja vacío se generará uno de forma aleatoria - Luego se puede cambiar.</string>\r\n"
	    		+ "    <string name=\"registro_user_created\">El Usuario fue Creado</string>\r\n"
	    		+ "    <string name=\"password_old_new_equals\">La contraseña Nueva debe ser diferente al Actual</string>\r\n"
	    		+ "    <string name=\"password_validation__TOO_SHORT\">Debe tener al menos %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"password_validation__TOO_LONG\">Debe tener al menos  %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"addmember_activity__invitation_message__validate__caracteres_disponibles\">Caracteres disponibles %1$s.</string>\r\n"
	    		+ "    <string name=\"addmember_activity__invitation_code__validate__empty\">El código de invitación no puede estar vacío</string>\r\n"
	    		+ "    <string name=\"addmember_activity__send_invitation__success\">El Usuario ha sido Invitado</string>\r\n"
	    		+ "    <string name=\"grupo_activity__title\">Privacity - Grupos</string>\r\n"
	    		+ "    <string name=\"grupo_activity__query_hint\">Buscar título</string>\r\n"
	    		+ "    <string name=\"grupo_activity__powerservice__title\">SOLICITUD DE PERMISO</string>\r\n"
	    		+ "    <string name=\"grupo_activity__powerservice__detail\">En la siguiente pantalla se le solicitara permisos para poder continuar recibiendo mensajes cuando el móvil entre en modo reposo. La aplicación utiliza su propia recepción de mensajes, por seguridad descarta soluciones de terceros como las proporcionadas por Google. Garantizamos que no afectará en consumo de la batería, ni del consumo de datos más de lo estrictamente necesario.\\nSi acepta puede cambiar la configuración en cualquier momento. Si no acepta seguirá funcionando, pero en Modo Reposo no recibirá notificación alguna.</string>\r\n"
	    		+ "    <string name=\"grupo_activity__exit__cerrar_app\">Cerrar App</string>\r\n"
	    		+ "    <string name=\"grupo_activity__exit__cerrar_session\">Cerrar Sesión</string>\r\n"
	    		+ "    <string name=\"grupo_activity__exit__minimizar\">Minimizar</string>\r\n"
	    		+ "    <string name=\"grupo_activity__members__online__title\">Miembros</string>\r\n"
	    		+ "    <string name=\"grupo_activity__members__online__detail\">Conectados: %1$s de %2$s</string>\r\n"
	    		+ "    <string name=\"grupo_activity__invitation__response\">Responder a la solicitud</string>\r\n"
	    		+ "    <string name=\"grupo_activity__invitation__response_details1\">Ha sido invitado por %1$s</string>\r\n"
	    		+ "    <string name=\"grupo_activity__invitation__response_details2\">Con el rol de  %1$s</string>\r\n"
	    		+ "    <string name=\"imagefull_activity__title\">Visor de Imagen</string>\r\n"
	    		+ "    <string name=\"imagefull_activity__validation__download__not_allowed\">La configuración del Mensaje no permite la descarga</string>\r\n"
	    		+ "    <string name=\"imagefull_activity__validation__download__success\">Archivo Descargado</string>\r\n"
	    		+ "    <string name=\"lock_activity__validation__password__fail\">Contraseña Incorrecta\\nIntento %1$s de %2$s</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__title\">Privacity - Crear Grupo</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__grupo_created\">GRUPO CREADO</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__alert__error_encrypt_title\">ERROR ENCRIPTACION</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__submit\">Crear</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__add_new_member\">Agregar un Integrante</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__goto_grupoinfo\">Información del Grupo</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__create_another_grupo\">crear nuevo grupo</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__go_back\">Volver</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__name_grupo__hint\">Nombre del Nuevo Grupo</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__generate_and_save\">Generar Nuevo y Guardar</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__title\">Código de Invitación</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__reset\">Reestablecer</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__save\">Guardar</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__codigo_sin_cambios\">Código sin cambios</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__codigo_validate__empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__codigo_validate__no_save\">Debe Guardar o restablecer para compartir</string>\r\n"
	    		+ "    <string name=\"acodigoinvitacion_activity__alert__error_generated_title\">Error generando Código de Invitación</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__save__ok\">Guardado</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__share__message__body\">Mi código de invitación es: %1$s</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__share__message__extra_subject\">Únete a la app de mensajería más segura del mundo</string>\r\n"
	    		+ "    <string name=\"grupo_info__lock_title\">Contraseña y Bloqueo</string>\r\n"
	    		+ "    <string name=\"grupo_info_password_enabled\">Contraseña Activado</string>\r\n"
	    		+ "    <string name=\"grupo_info_lock_enabled\">Cerrar la conversación</string>\r\n"
	    		+ "    <string name=\"grupo_info_lock__detail_message\">La contraseña esta activo en la aplicación solamente. Si desea más seguridad incluya un Extra Encrypt.</string>\r\n"
	    		+ "    <string name=\"mainconfiguracion_activity__validation__error__url\">URL invalida</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__desconexiones\">Desconexiones:</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__reintentos_total\">Reintentos Total:</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__intentar_reconecta_en\">Intentar reconectar en</string>\r\n"
	    		+ "    <string name=\"general__segundos\">segundos</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__reconnet_trying\">reconexión - reintentando...</string>\r\n"
	    		+ "    <string name=\"my_account_conf_descarga_imagen_txt\">Bloquear la Descarga de las Imagenes y Videos de mis envios</string>\r\n"
	    		+ "    <string name=\"my_account_conf_gen_ocultar_estado_txt\">Ocultar la Lectura de los Mensajes Recibidos</string>\r\n"
	    		+ "    <string name=\"my_account_conf__block_resend__txt\">Bloquear el Reenvío de Mis Mensajes</string>\r\n"
	    		+ "    <string name=\"my_account_conf_temporal_obligatorio_txt\">Enviar Siempre Mensajes Temporales</string>\r\n"
	    		+ "    <string name=\"my_account_conf_temporal_maximo_tiempo_permitido_titulo\">Tiempo</string>\r\n"
	    		+ "    <string name=\"my_account_conf_black_obligatorio_adjunto_txt\">Enviar Siempre Imágenes y Videos en modo Black</string>\r\n"
	    		+ "    <string name=\"my_account_conf_black_obligatorio_adjunto_recibido_txt\">Recibir Siempre Imágenes y Videos en modo Black</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"my_account_activity__title\">Mi cuenta</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__server_disconnectad\">Desconectado del servidor</string>\r\n"
	    		+ "    <string name=\"frame_my_account__password_title\">Cambiar Contraseña</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info_nickname__generator\">Generar un Nickname Aleatorio</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info_nickname__message_info\">Si se deja en blanco se usará el Nickname General que actualmente es: %1$s</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info_nickname__title\">NICKNAME PARA TU USUARIO</string>\r\n"
	    		+ "    <string name=\"message_activity__allow_audio__not_allow\">La configuración del grupo no permite enviar mensajes de audio</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__audio_max_time\">Tiempo Máximo</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__random_nickname_txt\">Usar Nickname Aleatorio para todos los integrantes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__hide_member_list_txt\">Ocultar Lista de Integrantes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__hide_message_read_state_txt\">Ocultar Estado Leído de los Mensajes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__hide_message_details_txt\">Ocultar Detalles de los Mensajes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__black_message_attach_mandatory_txt\">Modo Black Obligatorio cuando contenga Imágenes y/o Videosk</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__block_resend_txt\">Bloquear reenvio</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__title\">CONFIGURACIONES GENERALES</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__name_title\">Configuración Personal</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__name_personal__title\">Configuración Personal</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__accept_and_send\">Aceptar e\\nInvitar a alguien más</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__accept_and_close\">Aceptar y Cerrar</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__add_message_invitation\">Agrega un mensaje para tu invitado</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__codigo_invitation__hint\">Código de Invitación</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__codigo_invitation__scan_qr\">Escanear QR</string>\r\n"
	    		+ "    <string name=\"frame_my_account_gral_conf_title\">CONFIGURACIONES GENERALES</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock_activar\">Bloqueo Activado</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock_validate_min_seconds\">Debe tener al menos %1$s segundos</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock_mensaje\">Si activa esta opción a la cantidad de minutos establecidos se mostrará una pantalla de bloqueo en donde habría de escribir nuevamente la contraseña.</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock\">Bloqueo de la App</string>\r\n"
	    		+ "    <string name=\"frame_my_account_login_skip__activar\">Saltar Autentificación Activado</string>\r\n"
	    		+ "    <string name=\"frame_my_account_nickname__generator\">Generar un Nickname Aleatorio</string>\r\n"
	    		+ "    <string name=\"frame_my_account_nickname__title\">NICKNAME PARA TU USUARIO</string>\r\n"
	    		+ "    <string name=\"frame_my_account_loguin_skip__title\">Saltar pantalla de ingreso</string>\r\n"
	    		+ "    <string name=\"message_detail_activity__hide_read_message\">Se oculta a los miembros del grupo que has leído este mensaje</string>\r\n"
	    		+ "    <string name=\"message_detail__hide_state_grupo_txt\">El grupo está configurado para ocultar el estado de todos los mensajes, solo tú puedes ver el estado de tu actividad</string>\r\n"
	    		+ "    <string name=\"message_detail_activity__title\">Privacity – Detalles del Mensaje</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_grupo_info__member__title\">Integrantes</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__hide_member__admin_message_txt\">El grupo está configurado para que unicamente el Administrador pueda ver la lista completa de Integrantes</string>\r\n"
	    		+ "    <string name=\"privacity_environment\">General</string>\r\n"
	    		+ "    <string name=\"app_name\">Privacity</string>\r\n"
	    		+ "    <string name=\"error_codigo\">ERROR CÓDIGO</string>\r\n"
	    		+ "    <string name=\"ok\">OK</string>\r\n"
	    		+ "    <string name=\"close\">Cerrar</string>\r\n"
	    		+ "    <string name=\"cancel\">Cancelar</string>\r\n"
	    		+ "    <string name=\"error_code__CL_V_1001\">EL CAMPO DE VALIDACIÓN DEL CLIENTE ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__GI_000\">GENERAL INESPERADO</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1000\">GENERAL ACCESO INVÁLIDO</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1001\">GENERAL NO GUARDAR PORQUE NO HAY CAMBIOS DE DATOS</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1002\">GENERAL SIN ACCESO A INTERNET</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1003\">GENERAL PROTOCOLO DE ACCESO INVÁLIDO</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1004\">GENERAL DATOS ENVIADOS INVÁLIDOS</string>\r\n"
	    		+ "    <string name=\"error_code__G_1000\">EL GRUPO USUARIO NO EXISTE CÓDIGO DE INVITACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__G_1001\">EL GRUPO USUARIO ESTÁ EN EL GRUPO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1002\">EL GRUPO ID DE GRUPO MAL FORMATO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1003\">EL GRUPO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__G_1004\">EL GRUPO USUARIO NO ESTÁ EN EL GRUPO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1005\">EL GRUPO USUARIO NO TIENE PERMISO EN ESTE GRUPO PARA AGREGAR MIEMBROS</string>\r\n"
	    		+ "    <string name=\"error_code__G_1006\">EL ROL DE GRUPO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__G_1007\">EL CÓDIGO DE INVITACIÓN DE USUARIO DE GRUPO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1008\">LA INVITACIÓN DE GRUPO EXISTE INVITACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__G_1009\">LA INVITACIÓN DE USUARIO DE GRUPO NO PUEDE SER LA MISMA</string>\r\n"
	    		+ "    <string name=\"error_code__G_1010\">EL GRUPO USUARIO NO PUEDE ENVIAR MENSAJE</string>\r\n"
	    		+ "    <string name=\"error_code__G_1011\">EL GRUPO USUARIO NO PUEDE ENVIAR MENSAJE DE SÓLO LECTURA</string>\r\n"
	    		+ "    <string name=\"error_code__G_1012\">GRUPO GENERAL CONF LOCK MIN SEGUNDOS VALIDACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__G_1013\">ROL GRUPO NO PERMITIR ESTA ACCIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1000\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA ANTERIOR ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1001\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA NUEVA ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1002\">CAMBIAR CONTRASEÑA VALIDACIÓN CONFIRMAR CONTRASEÑA NUEVA ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1003\">CAMBIAR CONTRASEÑA VALIDACIÓN NUEVA CONTRASEÑA ES DIFERENTE NUEVA CONFIRMAR CONTRASEÑA</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1004\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA ANTERIOR INCORRECTA</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1005\">CAMBIAR CONTRASEÑA VALIDACIÓN NUEVA CONTRASEÑA ES IGUAL CONTRASEÑA ANTERIOR</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1008\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA ANTERIOR ES DIFERENTE A LA CONTRASEÑA REGISTRADA</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1006\">CAMBIAR CONTRASEÑA VALIDACIÓN NOMBRE USUARIO INCORRECTO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_10007\">CAMBIAR CONTRASEÑA VALIDACIÓN NOMBRE USUARIO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__Z_1001\">COMPRIMIR ZIP</string>\r\n"
	    		+ "    <string name=\"error_code__Z_1002\">DESCOMPRIMIR ZIP</string>\r\n"
	    		+ "    <string name=\"error_code__DC_1001\">CONVERTIR BYTES DATOS A CADENA</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1000\">LONGITUD INCORRECTA ID DE PETICIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1001\">ID DE PETICIÓN NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1002\">ID DE SOLICITUD EXPIRÁ</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1003\">ID DE SOLICITUD NO PUEDE SER NULO</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1004\">ID DE SOLICITUD NO PUEDE USARSE VARIAS VECES</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"error_code__U_1000\">EL SISTEMA DE USUARIO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__U_1001\">EL USUARIO NO REGISTRA DEL USUARIO</string>\r\n"
	    		+ "    <string name=\"error_code__U_1002\">EL APODEMOS DE USUARIO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__U_1003\">NOMBRE DE USUARIO DEMASIADO LARGO</string>\r\n"
	    		+ "    <string name=\"error_code__U_1004\">NOMBRE DE USUARIO DEMASIADO CORT0</string>\r\n"
	    		+ "    <string name=\"error_code__U_1005\">USUARIO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__A_1000\">NOMBRE DE USUARIO AUTORIZADO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__A_1001\">NOMBRE DE USUARIO AUTORIZADO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__A_1002\">NOMBRE DE USUARIO AUTORIZADO ES DEMASIADO CORT0</string>\r\n"
	    		+ "    <string name=\"error_code__A_1003\">El Usuario y/o Contraseña\\n son Inválidos</string>\r\n"
	    		+ "    <string name=\"error_code__recomendacion__A_1003\">Verifique los datos y vuelva a intentarlo</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"error_code__RI_1005\">El Servidor está en Mantenimiento</string>\r\n"
	    		+ "    <string name=\"error_code__recomendacion__RI_1005\">Vuelva a intentarlo en un unos minutos</string>\r\n"
	    		+ "    <string name=\"error_code__A_1004\">SESIÓN DE AUTENTICACIÓN FUERA DE SINCRONIZACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__A1005\">FALLO DE OBTENCIÓN DE TOKEN DE AUTENTICACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__M_1000\">MENSAJE ID MENSAJE MAL FORMATO</string>\r\n"
	    		+ "    <string name=\"error_code__M_1001\">MENSAJE NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__M_1002\">MENSAJE NO CREADOR MENSAJE</string>\r\n"
	    		+ "    <string name=\"error_code__MDD_1001\">MEDIADATA NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1000\">DETALLE MENSAJE ID DETALLE MENSAJE MAL FORMATO</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1001\">DETALLE MENSAJE NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1002\">DETALLE DEL MENSAJE ELIMINADO</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1003\">DETALLE DEL MENSAJE NO EXISTE HORA DEL MENSAJE</string>\r\n"
	    		+ "    <string name=\"error_code__MY_1000\">CÓDIGO DE INVITACIÓN DE MI CUENTA NO DISPONIBLE</string>\r\n"
	    		+ "    <string name=\"error_code__MY_1001\">CÓDIGO DE INVITACIÓN DE MI CUENTA NO PUEDE ESTAR VACÍO</string>\r\n"
	    		+ "    <string name=\"error_code__MY_1002\">VALIDACIÓN DE SEGUNDOS DE BLOQUEO DE MI CUENTA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1000\">ENCRYPT IS NULL</string>\r\n"
	    		+ "    <string name=\"error_code__E_1001\">LA CLAVE PRIVADA DE ENCRIPTACIÓN ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1002\">LA CLAVE PÚBLICA DE ENCRIPTACIÓN ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1003\">LA CLAVE PÚBLICA DE ENCRIPTACIÓN NO ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1006\">LA INVITACIÓN DE CLAVE PÚBLICA DE ENCRIPTACIÓN DEBE SER NULA</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1001\">PROCESO DE ENCRIPTACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__DP_1001\">PROCESO DE DESENCRIPTACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1003\">LA AES DE ENCRIPTACIÓN ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1004\">LA CLAVE SECRETA DE ENCRYPT AES ES NULL</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1005\">LA SAL DE ENCRYPT AES ES NULL</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1007\">FALLO DE CREACIÓN DE ENCRYPT AES</string>\r\n"
	    		+ "    <string name=\"error_code__DID_1001\">FALLO DE PROCESO DE DESCRYPT ID</string>\r\n"
	    		+ "    <string name=\"error_code__EID_1001\">FALLO DE PROCESO DE ENCRYPT ID</string>\r\n"
	    		+ "    <string name=\"error_code__WE_1001\">MENSAJERÍA SIN CONEXIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__ME_1002\">PROTOCOLO DE ACCESO NO VÁLIDO DE MENSAJERÍA</string>\r\n"
	    		+ "    <string name=\"error_code__WE_1003\">ERROR AL OBTENER MIEMBROS EN LÍNEA DE MENSAJERÍA</string>\r\n"
	    		+ "    <string name=\"error_code__SM_1001\">ADMINISTRADOR DE SESIÓN DESCONECTADO</string>\r\n"
	    		+ "    <string name=\"error_code__HC_1001\">PING DEL COMPROBADOR DE ESTADO SIN RESPUESTA</string>\r\n"
	    		+ "    <string name=\"error_code__IP_1003\">ERROR GENERAL DEL PROVEEDOR DE IDS</string>\r\n"
	    		+ "    <string name=\"error_code__IP_1001\">PROVEEDOR DE IDS DESCONECTADO</string>\r\n"
	    		+ "    <string name=\"error_code__IP_1002\">NO SE DEBE INVOCAR LA ACTUALIZACIÓN DEL PROVEEDOR DE IDS EN ESTE CASO</string>\r\n"
	    		+ "    <string name=\"error_code__KL_1001\">ERROR DE BLOQUEO DE TECLAS</string>\r\n"
	    		+ "    <string name=\"error_code__KL_1002\">ERROR DE ACTUALIZACIÓN DE BLOQUEO DE TECLA</string>\r\n"
	    		+ "    <string name=\"error_code__M_1003\">El mensaje original esta configurado para bloquear su reenvio</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__ADMIN\">Un Administrador te asigno el Rol de Admin</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__READONLY\">Un Administrador te asigno el Rol de Solo Lectura</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__MODERATOR\">Un Administrador te asigno el Rol de Moderador</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__MEMBER\">Un Administrador te asigno el Rol de Miembro</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__bloque_de_emergencia\">Bloque de Emergencia</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__lock_config__modified\">UN ADMINISTRADOR HA MODIFICADO LA CONFIGURACION DE BLOQUEO DEL GRUPO</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__general_config__modified\">UN ADMINISTRADOR HA MODIFICADO LA CONFIGURACION GENERAL DEL GRUPO</string>\r\n"
	    		+ "</resources>";
	            

	   String traduccion="Se o problema persistir, informe @\r\n"
	   		+ "Ativado @\r\n"
	   		+ "Desligado			@\r\n"
	   		+ "Não configurado @\r\n"
	   		+ "Permitido @\r\n"
	   		+ "Bloqueado @\r\n"
	   		+ "Obrigatório			@\r\n"
	   		+ "frame_help__common__messaging__reconnect @\r\n"
	   		+ "frame_help__frame_minha_conta__bloqueio @\r\n"
	   		+ "A palavra latina paragraphus foi transformada em paragraph, um termo comumente usado no campo da gramática. São os diferentes fragmentos de um texto, que podem ser reconhecidos pela letra maiúscula no início e pelo ponto final.\\r\\n \\r\\n Um parágrafo pode ser composto por uma ou mais frases. Cada um deles é separado do outro por um ponto. As frases, por sua vez, são conjuntos de palavras que compõem uma unidade de significado. Se continuarmos a decompor os elementos, também podemos afirmar que as palavras são criadas a partir da combinação de letras. @\r\n"
	   		+ "item_list_view_message_detail__state__minha_mensagem_error_not_send @\r\n"
	   		+ "item_lista_visualização_detalhe_mensagem_estado_mensagem_enviada @\r\n"
	   		+ "item_lista_visualização_detalhe_mensagem_estado_mensagem_envio @\r\n"
	   		+ "item_lista_visualização_mensagem_detalhe_estado_destino_servidor @\r\n"
	   		+ "item_lista_visualização_mensagem_detalhe_estado_destino_entregue @\r\n"
	   		+ "item_lista_visualização_mensagem_detalhe_estado_destino_leitura_oculto @\r\n"
	   		+ "item_lista_visualização_mensagem_detalhe_estado__destino_leitura @\r\n"
	   		+ "É uma mensagem com Anônimo enviando @\r\n"
	   		+ "Download bloqueado @\r\n"
	   		+ "message_detail__icon__random_nickname @\r\n"
	   		+ "É uma mensagem de áudio @\r\n"
	   		+ "ícone_de_detalhes_da_mensagem_está_ocultar_estado_de_leitura_da_mensagem @\r\n"
	   		+ "É uma mensagem temporária @\r\n"
	   		+ "Contém uma imagem @\r\n"
	   		+ "É uma mensagem encaminhada @\r\n"
	   		+ "É uma resposta a outra mensagem @\r\n"
	   		+ "Possui criptografia extra @\r\n"
	   		+ "Mensagem com bloqueio de encaminhamento @\r\n"
	   		+ "É uma mensagem no Modo Preto @\r\n"
	   		+ "Mensagem sem bloqueio de encaminhamento @\r\n"
	   		+ "Bloquear mensagens de áudio @\r\n"
	   		+ "Tamanho máximo @\r\n"
	   		+ "Tamanho mínimo @\r\n"
	   		+ "Senha			@\r\n"
	   		+ "Papel @\r\n"
	   		+ "Mensagens vazias @\r\n"
	   		+ "Carregar 10 mensagens anteriores @\r\n"
	   		+ "Adicionar contato ao grupo @\r\n"
	   		+ "Informações do grupo @\r\n"
	   		+ "Senha atual @\r\n"
	   		+ "@\r\n"
	   		+ "Confirmação @\r\n"
	   		+ "Manter			@\r\n"
	   		+ "Salvar e Fechar @\r\n"
	   		+ "Confirmar @\r\n"
	   		+ "Você tem certeza? @\r\n"
	   		+ "Cancelar @\r\n"
	   		+ "Aceitar			@\r\n"
	   		+ "Exemplo Exemplo Exemplo Exemplo приклад @\r\n"
	   		+ "Detalhes			@\r\n"
	   		+ "Reiniciar @\r\n"
	   		+ "Ignorar @\r\n"
	   		+ "Salvo @\r\n"
	   		+ "Compartilhar			@\r\n"
	   		+ "Disponível			@\r\n"
	   		+ "Não disponível @\r\n"
	   		+ "Recomendado @\r\n"
	   		+ "Reiniciar @\r\n"
	   		+ "Erro: %1$s @\r\n"
	   		+ "código: %1$s - sem descrição @\r\n"
	   		+ "Mensagem de erro @\r\n"
	   		+ "Mensagem de erro: %1$s @\r\n"
	   		+ "Erro ao chamar o servidor: %1$s @\r\n"
	   		+ "Administrador @\r\n"
	   		+ "Moderador @\r\n"
	   		+ "Não há alterações para salvar @\r\n"
	   		+ "Idioma e exibição @\r\n"
	   		+ "Membro @\r\n"
	   		+ "Somente leitura @\r\n"
	   		+ "Anônimo @\r\n"
	   		+ "Temporário @\r\n"
	   		+ "Preto @\r\n"
	   		+ "Extra Criptografado @\r\n"
	   		+ "Senha incorreta @\r\n"
	   		+ "Esta tela é somente para administradores. Sua função é %1$s @\r\n"
	   		+ "Erro			@\r\n"
	   		+ "Enviando @\r\n"
	   		+ "Enviado			@\r\n"
	   		+ "Servidor @\r\n"
	   		+ "Entregue			@\r\n"
	   		+ "Ler @\r\n"
	   		+ "Ação não permitida. Seu papel no grupo é %1$s @\r\n"
	   		+ "Não há dados para copiar @\r\n"
	   		+ "Copiado @\r\n"
	   		+ "Copiar @\r\n"
	   		+ "Criar grupo @\r\n"
	   		+ "Código de convite @\r\n"
	   		+ "Minha conta @\r\n"
	   		+ "Sobre			@\r\n"
	   		+ "Sair			@\r\n"
	   		+ "Convite aceito @\r\n"
	   		+ "Informações do grupo: %1$s @\r\n"
	   		+ "Você saiu do grupo @\r\n"
	   		+ "Grupo excluído @\r\n"
	   		+ "Bloco Remoto @\r\n"
	   		+ "Digite sua senha para executar esta ação @\r\n"
	   		+ "Membros @\r\n"
	   		+ "Adicionar novo membro @\r\n"
	   		+ "Envio especial @\r\n"
	   		+ "Excluir para meu @\r\n"
	   		+ "Excluir para todos @\r\n"
	   		+ "Excluir para todos e @encaminhamentos\r\n"
	   		+ "Eliminar @\r\n"
	   		+ "Avançar @\r\n"
	   		+ "Responder			@\r\n"
	   		+ "Tentar novamente @\r\n"
	   		+ "O AudioTrack não pôde ser inicializado, verifique a configuração @\r\n"
	   		+ "Você deseja excluir a Chave de Criptografia Extra? @\r\n"
	   		+ "Digite a chave de criptografia extra @\r\n"
	   		+ "Avançar @\r\n"
	   		+ "Mensagem(ns) encaminhada(s) @\r\n"
	   		+ "Erro ao encaminhar @\r\n"
	   		+ "Registre-se @\r\n"
	   		+ "Entre em @\r\n"
	   		+ "Usuário @\r\n"
	   		+ "Senha			@\r\n"
	   		+ "Sem Internet @\r\n"
	   		+ "Verifique sua conexão com a internet. @\r\n"
	   		+ "Não pode estar vazio @\r\n"
	   		+ "Não pode estar vazio @\r\n"
	   		+ "Privacidade @\r\n"
	   		+ "O servidor configurado não está respondendo @\r\n"
	   		+ "Verifique as configurações @\r\n"
	   		+ "ERRO			@\r\n"
	   		+ "Descanso em execução: %1$s @\r\n"
	   		+ "@ Configuração\r\n"
	   		+ "Espanhol			@\r\n"
	   		+ "Inglês @\r\n"
	   		+ "Versão %1$s @\r\n"
	   		+ "Algum grupo enviou um bloco remoto @\r\n"
	   		+ "Usuário @\r\n"
	   		+ "Senha			@\r\n"
	   		+ "Confirmar @\r\n"
	   		+ "* Obrigatório @\r\n"
	   		+ "CRIAR UMA CONTA @\r\n"
	   		+ "Processando @\r\n"
	   		+ "Inscrição @\r\n"
	   		+ "O usuário não pode estar vazio @\r\n"
	   		+ "O usuário deve ter pelo menos %1$ @ caracteres\r\n"
	   		+ "O usuário deve ter no máximo %1$ caracteres @\r\n"
	   		+ "O apelido não pode estar vazio @\r\n"
	   		+ "O apelido deve ter no máximo %1$s @ caracteres\r\n"
	   		+ "O nome de usuário já foi escolhido @\r\n"
	   		+ "O nome de usuário é válido @\r\n"
	   		+ "Há erros na validação @\r\n"
	   		+ "Deve ser diferente do @ atual\r\n"
	   		+ "As senhas são diferentes @\r\n"
	   		+ "Deve ter pelo menos %1$s @ caracteres\r\n"
	   		+ "Poderia ter pelo menos %1$s @ caracteres\r\n"
	   		+ "Deve ter no máximo %1$s @ caracteres\r\n"
	   		+ "Não pode estar vazio @\r\n"
	   		+ "Não pode conter espaços @\r\n"
	   		+ "Não pode conter espaços @\r\n"
	   		+ "Deve ter pelo menos %1$s caractere especial @\r\n"
	   		+ "Deve ter pelo menos %1$s caracteres especiais @\r\n"
	   		+ "Tenha pelo menos %1$s caractere especial @\r\n"
	   		+ "Tenha pelo menos %1$s caracteres especiais @\r\n"
	   		+ "Sugestão: @\r\n"
	   		+ "Muito seguro @\r\n"
	   		+ "Deve ter pelo menos %1$s letras maiúsculas @\r\n"
	   		+ "Deve ter pelo menos %1$s letras maiúsculas @\r\n"
	   		+ "Tenha pelo menos %1$s de capital @\r\n"
	   		+ "Tenha pelo menos %1$s @ maiúsculo\r\n"
	   		+ "Deve ter pelo menos %1$s @ minúsculo\r\n"
	   		+ "Deve ter pelo menos %1$s @ minúsculo\r\n"
	   		+ "Tenha pelo menos %1\r\n"
	   		+ "$s minúsculos @\r\n"
	   		+ "Tenha pelo menos %1$s @ minúsculo\r\n"
	   		+ "Deve ter pelo menos %1$s número @\r\n"
	   		+ "Deve ter pelo menos %1$s números @\r\n"
	   		+ "Tenha pelo menos %1$s número @\r\n"
	   		+ "Tenha pelo menos %1$s números @\r\n"
	   		+ "Não é possível ter %1$s caracteres consecutivos @\r\n"
	   		+ "Pode não ter %1$s caracteres consecutivos @\r\n"
	   		+ "O usuário não pode estar presente @\r\n"
	   		+ "O usuário pode não estar presente @\r\n"
	   		+ "O apelido não pode estar presente @\r\n"
	   		+ "O apelido pode não estar presente @\r\n"
	   		+ "A senha não pode estar presente @\r\n"
	   		+ "A senha pode não estar presente @\r\n"
	   		+ "A senha é válida @\r\n"
	   		+ "As senhas estão corretas @\r\n"
	   		+ "Se deixado em branco, um será gerado aleatoriamente. Isso pode ser alterado. @\r\n"
	   		+ "O usuário foi criado em\r\n"
	   		+ "A nova senha deve ser diferente da atual @\r\n"
	   		+ "Deve ter pelo menos %1$s @ caracteres\r\n"
	   		+ "Deve ter pelo menos %1$s @ caracteres\r\n"
	   		+ "Personagens disponíveis %1$s. @\r\n"
	   		+ "O código de convite não pode estar vazio @\r\n"
	   		+ "O usuário foi convidado @\r\n"
	   		+ "Privacidade - Grupos @\r\n"
	   		+ "Título da pesquisa @\r\n"
	   		+ "PEDIDO DE PERMISSÃO @\r\n"
	   		+ "Na próxima tela, você será solicitado a dar permissão para continuar recebendo mensagens quando seu telefone entrar no modo de espera. O aplicativo usa seu próprio serviço de mensagens, mas, por motivos de segurança, descarta soluções de terceiros, como as fornecidas pelo Google. Garantimos que isso não afetará o consumo de bateria ou dados mais do que o estritamente necessário. Se você aceitar, poderá alterar as configurações a qualquer momento. Se você não aceitar, ele continuará funcionando, mas no Modo de Suspensão você não receberá nenhuma notificação. @\r\n"
	   		+ "Fechar aplicativo @\r\n"
	   		+ "Sair @\r\n"
	   		+ "Minimizar @\r\n"
	   		+ "Membros @\r\n"
	   		+ "Online: %1$s de %2$s @\r\n"
	   		+ "Responder à solicitação @\r\n"
	   		+ "Você foi convidado por %1$s @\r\n"
	   		+ "Com o papel de %1$s @\r\n"
	   		+ "Visualizador de imagens @\r\n"
	   		+ "As configurações de mensagem não permitem o download de @\r\n"
	   		+ "Arquivo baixado @\r\n"
	   		+ "Senha incorreta\\nTentativa %1$s de %2$s @\r\n"
	   		+ "Privacidade - Criar Grupo @\r\n"
	   		+ "GRUPO CRIADO @\r\n"
	   		+ "ERRO DE CRIPTOGRAFIA @\r\n"
	   		+ "Criar			@\r\n"
	   		+ "Adicionar um membro @\r\n"
	   		+ "Informações do grupo @\r\n"
	   		+ "criar novo grupo @\r\n"
	   		+ "Retornar			@\r\n"
	   		+ "Novo nome do grupo @\r\n"
	   		+ "Gerar novo e salvar @\r\n"
	   		+ "Código de convite @\r\n"
	   		+ "Reiniciar @\r\n"
	   		+ "Manter			@\r\n"
	   		+ "Código inalterado @\r\n"
	   		+ "Não pode estar vazio @\r\n"
	   		+ "Você deve salvar ou redefinir para compartilhar @\r\n"
	   		+ "Erro ao gerar código de convite @\r\n"
	   		+ "Salvo @\r\n"
	   		+ "Meu código de convite é: %1$s @\r\n"
	   		+ "Junte-se ao aplicativo de mensagens mais seguro do mundo @\r\n"
	   		+ "Senha e @ Lock\r\n"
	   		+ "Senha ativada @\r\n"
	   		+ "Feche a conversa @\r\n"
	   		+ "A senha fica ativa somente no aplicativo. Se você quiser mais segurança, inclua uma Criptografia Extra. @\r\n"
	   		+ "URL inválida @\r\n"
	   		+ "Desconexões: @\r\n"
	   		+ "Total de tentativas: @\r\n"
	   		+ "Tente reconectar em @\r\n"
	   		+ "segundos @\r\n"
	   		+ "reconexão - tentando novamente... @\r\n"
	   		+ "Bloquear o download de imagens e vídeos das minhas postagens @\r\n"
	   		+ "Ocultar Leitura de Mensagens Recebidas @\r\n"
	   		+ "Bloquear o encaminhamento das minhas mensagens @\r\n"
	   		+ "Sempre envie mensagens temporárias @\r\n"
	   		+ "Tempo			@\r\n"
	   		+ "Sempre envie imagens e vídeos no modo Preto @\r\n"
	   		+ "Receba sempre imagens e vídeos no modo preto @\r\n"
	   		+ "Minha conta @\r\n"
	   		+ "Desconectado do servidor @\r\n"
	   		+ "Alterar a senha @\r\n"
	   		+ "Gerar um apelido aleatório @\r\n"
	   		+ "Se deixado em branco, o apelido geral será usado, que atualmente é: %1$s @\r\n"
	   		+ "APELIDO PARA SEU USUÁRIO @\r\n"
	   		+ "As configurações do grupo não permitem o envio de mensagens de áudio @\r\n"
	   		+ "Tempo Máximo @\r\n"
	   		+ "Use apelido aleatório para todos os membros @\r\n"
	   		+ "Ocultar lista de membros @\r\n"
	   		+ "Ocultar status de leitura de @ mensagens\r\n"
	   		+ "Ocultar detalhes da mensagem @\r\n"
	   		+ "Modo preto obrigatório quando contém imagens e/ou vídeos\r\n"
	   		+ "Encaminhamento de bloco @\r\n"
	   		+ "CONFIGURAÇÕES GERAIS @\r\n"
	   		+ "Configurações pessoais @\r\n"
	   		+ "Configurações pessoais @\r\n"
	   		+ "Aceitar e\\nConvidar outra pessoa @\r\n"
	   		+ "Aceitar e Fechar @\r\n"
	   		+ "Adicione uma mensagem para seu convidado @\r\n"
	   		+ "Código de convite @\r\n"
	   		+ "Escaneie o QR @\r\n"
	   		+ "CONFIGURAÇÕES GERAIS @\r\n"
	   		+ "Bloqueio ativado @\r\n"
	   		+ "Deve ter pelo menos %1$s segundos @\r\n"
	   		+ "Se você ativar esta opção, uma tela de bloqueio aparecerá após o número definido de minutos, onde você terá que digitar a senha novamente. @\r\n"
	   		+ "Bloqueio de aplicativo @\r\n"
	   		+ "Pular autenticação habilitada @\r\n"
	   		+ "Gerar um apelido aleatório @\r\n"
	   		+ "APELIDO PARA SEU USUÁRIO @\r\n"
	   		+ "Pular tela de login @\r\n"
	   		+ "Está oculto aos membros do grupo que você leu esta mensagem @\r\n"
	   		+ "O grupo está configurado para ocultar o status de todas as mensagens, somente você pode ver o status da sua atividade @\r\n"
	   		+ "Privacidade – Detalhes da mensagem @\r\n"
	   		+ "Membros @\r\n"
	   		+ "O grupo está configurado para que somente o Administrador possa ver a lista completa de Membros @\r\n"
	   		+ "Em geral			@\r\n"
	   		+ "Privacidade @\r\n"
	   		+ "CÓDIGO DE ERRO @\r\n"
	   		+ "OK @\r\n"
	   		+ "Fechar			@\r\n"
	   		+ "Cancelar @\r\n"
	   		+ "O CAMPO DE VALIDAÇÃO DO CLIENTE É NULO @\r\n"
	   		+ "GENERAL INESPERADO @\r\n"
	   		+ "ACESSO INVÁLIDO GERAL @\r\n"
	   		+ "GERAL NÃO SALVE PORQUE NÃO HÁ ALTERAÇÕES DE DADOS @\r\n"
	   		+ "GERAL SEM ACESSO À INTERNET @\r\n"
	   		+ "PROTOCOLO GERAL DE ACESSO INVÁLIDO @\r\n"
	   		+ "DADOS INVÁLIDOS GERAIS ENVIADOS @\r\n"
	   		+ "GRUPO DE USUÁRIOS NÃO EXISTE CÓDIGO DE CONVITE @\r\n"
	   		+ "O GRUPO DE USUÁRIOS ESTÁ NO GRUPO @\r\n"
	   		+ "O ID DO GRUPO É INFORMADO @\r\n"
	   		+ "O GRUPO NÃO EXISTE @\r\n"
	   		+ "\r\n"
	   		+ "O GRUPO DE USUÁRIOS NÃO ESTÁ NO GRUPO @\r\n"
	   		+ "O USUÁRIO DO GRUPO NÃO TEM PERMISSÃO NESTE GRUPO PARA ADICIONAR MEMBROS @\r\n"
	   		+ "A FUNÇÃO DO GRUPO NÃO EXISTE @\r\n"
	   		+ "O CÓDIGO DE CONVITE DO USUÁRIO DO GRUPO É NULO @\r\n"
	   		+ "CONVITE DE GRUPO EXISTE CONVITE @\r\n"
	   		+ "O CONVITE DO USUÁRIO DO GRUPO NÃO PODE SER O MESMO @\r\n"
	   		+ "GRUPO DE USUÁRIOS NÃO PODE ENVIAR MENSAGEM @\r\n"
	   		+ "GRUPO DE USUÁRIOS NÃO PODE ENVIAR MENSAGEM SOMENTE LEITURA @\r\n"
	   		+ "GRUPO GERAL CONF BLOQUEIO MIN SEGUNDOS VALIDAÇÃO @\r\n"
	   		+ "FUNÇÃO DE GRUPO NÃO PERMITIR ESTA AÇÃO @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA SENHA ANTERIOR É NULA @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA NOVA SENHA É NULA @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA CONFIRMAR NOVA SENHA É NULA @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA NOVA SENHA É DIFERENTE NOVA CONFIRMAR SENHA @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA SENHA ANTERIOR INCORRETA @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA A NOVA SENHA É A MESMA QUE A SENHA ANTERIOR @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA A SENHA ANTERIOR É DIFERENTE DA SENHA REGISTRADA @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA NOME DE USUÁRIO INCORRETO @\r\n"
	   		+ "ALTERAR VALIDAÇÃO DE SENHA NOME DE USUÁRIO É NULO @\r\n"
	   		+ "CEP @\r\n"
	   		+ "DESCOMPRAR ZIP @\r\n"
	   		+ "CONVERTER BYTES DE DADOS EM STRING @\r\n"
	   		+ "ID DE SOLICITAÇÃO DE COMPRIMENTO INCORRETO @\r\n"
	   		+ "ID DA SOLICITAÇÃO NÃO EXISTE @\r\n"
	   		+ "O ID DO APLICATIVO EXPIRARÁ EM\r\n"
	   		+ "O ID DA SOLICITAÇÃO NÃO PODE SER NULO @\r\n"
	   		+ "O ID DO APLICATIVO NÃO PODE SER USADO VÁRIAS VEZES @\r\n"
	   		+ "O SISTEMA DO USUÁRIO NÃO EXISTE @\r\n"
	   		+ "USUÁRIO NÃO REGISTRA USUÁRIO @\r\n"
	   		+ "O APELIDO DO USUÁRIO É NULL @\r\n"
	   		+ "NOME DE USUÁRIO MUITO LONGO @\r\n"
	   		+ "NOME DE USUÁRIO MUITO CURTO @\r\n"
	   		+ "USUÁRIO NÃO EXISTE @\r\n"
	   		+ "NOME DE USUÁRIO AUTORIZADO EXISTE @\r\n"
	   		+ "NOME DE USUÁRIO AUTORIZADO É NULO @\r\n"
	   		+ "O NOME DO USUÁRIO AUTORIZADO É MUITO CURTO @\r\n"
	   		+ "O nome de usuário e/ou a senha são inválidos @\r\n"
	   		+ "Por favor, verifique seus dados e tente novamente @\r\n"
	   		+ "O servidor está em manutenção @\r\n"
	   		+ "Por favor, tente novamente em alguns minutos @\r\n"
	   		+ "SESSÃO DE AUT FORA DE SINCRONIA @\r\n"
	   		+ "FALHA EM OBTER TOKEN DE AUTENTICAÇÃO @\r\n"
	   		+ "ID DA MENSAGEM MENSAGEM EM FORMATO RUIM @\r\n"
	   		+ "MENSAGEM NÃO EXISTE @\r\n"
	   		+ "MENSAGEM NÃO MENSAGEM DO CRIADOR @\r\n"
	   		+ "MEDIADATA NÃO EXISTE @\r\n"
	   		+ "ID DETALHES DA MENSAGEM DETALHES DA MENSAGEM FORMATO RUIM @\r\n"
	   		+ "DETALHES DA MENSAGEM NÃO EXISTEM @\r\n"
	   		+ "DETALHE DA MENSAGEM EXCLUÍDA @\r\n"
	   		+ "DETALHES DA MENSAGEM O TEMPO DA MENSAGEM NÃO EXISTE @\r\n"
	   		+ "O CÓDIGO DE CONVITE DA MINHA CONTA NÃO ESTÁ DISPONÍVEL @\r\n"
	   		+ "O CÓDIGO DE CONVITE DA MINHA CONTA NÃO PODE ESTAR VAZIO @\r\n"
	   		+ "VALIDAÇÃO DE SEGUNDOS DE BLOQUEIO DA MINHA CONTA @\r\n"
	   		+ "ENCRYPT É NULL @\r\n"
	   		+ "A CHAVE DE CRIPTOGRAFIA PRIVADA É NULA @\r\n"
	   		+ "A CHAVE DE CRIPTOGRAFIA PÚBLICA É NULA @\r\n"
	   		+ "A CHAVE DE CRIPTOGRAFIA PÚBLICA NÃO É NULA @\r\n"
	   		+ "O CONVITE DE CHAVE PÚBLICA DE CRIPTOGRAFIA DEVE SER NULO @\r\n"
	   		+ "PROCESSO DE CRIPTOGRAFIA @\r\n"
	   		+ "PROCESSO DE DESCRIPTOGRAFIA @\r\n"
	   		+ "A CRIPTOGRAFIA AES É NULA @\r\n"
	   		+ "AES ENCRYPT SECRET CHAVE É NULA @\r\n"
	   		+ "AES ENCRYPT SALT É NULL @\r\n"
	   		+ "FALHA NA CRIAÇÃO DA CRIPTOGRAFIA AES @\r\n"
	   		+ "FALHA NO PROCESSO DE DESCRIÇÃO DE ID @\r\n"
	   		+ "FALHA NO PROCESSO DE ID DE CRIPTOGRAFIA @\r\n"
	   		+ "MENSAGENS OFFLINE @\r\n"
	   		+ "PROTOCOLO DE ACESSO DE MENSAGENS INVÁLIDO @\r\n"
	   		+ "ERRO AO COLOCAR MENSAGENS ONLINE DOS MEMBROS @\r\n"
	   		+ "GERENTE DE SESSÃO DESCONECTADO @\r\n"
	   		+ "VERIFICADOR DE STATUS PING SEM RESPOSTA @\r\n"
	   		+ "ERRO DO PROVEDOR DE IDENTIFICAÇÃO GERAL @\r\n"
	   		+ "PROVEDOR DE IDS DESCONECTADO @\r\n"
	   		+ "A ATUALIZAÇÃO DO PROVEDOR DE IDS NÃO DEVE SER IVOCADA NESTE CASO @\r\n"
	   		+ "ERRO DE BLOQUEIO DE TECLA @\r\n"
	   		+ "ERRO DE ATUALIZAÇÃO DE BLOQUEIO DE CHAVE @\r\n"
	   		+ "A mensagem original está definida para bloquear o encaminhamento @\r\n"
	   		+ "Um administrador atribuiu a você a função de administrador @\r\n"
	   		+ "Um administrador atribuiu a você a função somente leitura @\r\n"
	   		+ "Um administrador atribuiu a você a função de moderador @\r\n"
	   		+ "Um administrador atribuiu a você a função de membro @\r\n"
	   		+ "Bloco de emergência @\r\n"
	   		+ "UM ADMINISTRADOR MODIFICOU AS CONFIGURAÇÕES DE BLOQUEIO DE GRUPO @\r\n"
	   		+ "UM ADMINISTRADOR MODIFICOU AS CONFIGURAÇÕES GERAIS DO GRUPO @ \r\n";
	   
	   
	        JAXBContext jaxbContext;
	       
	          jaxbContext = JAXBContext.newInstance(Root.class);
	          Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
	          Root employee = (Root) jaxbUnmarshaller.unmarshal(new StringReader(xmlString));
	       //  System.out.println(employee);
	          //\t\t\t@
	          String[] x = traduccion.split("@");
	          for (int i = 0 ; i < employee.getString().length; i++) {
	        	///
	        	 //  System.out.println(employee.getString()[i].string + "\t\t\t@");
	        	 System.out.println("<string name=\"" +employee.getString()[i].name + "\">" + x[i].trim() +"</string>");
	          }


	}

}