package com.privacity.common.util;

import java.io.StringReader;

import com.privacity.common.model.Placeholder;
import com.privacity.common.model.Root;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.Unmarshaller;

public class CreateStringXML {


	public static void main(String[] args) throws Exception {

	    String xmlString = "<resources>              <string name=\"general__inform__problem\">Si el problema persiste informelo</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__on\">Activado</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__off\">Apagado</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__null\">Sin Configurar</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__allow\">Permitido</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__block\">Bloqueado</string>\r\n"
	    		+ "    <string name=\"frame_select_view__tooltip_text__mandatory\">Obligatorio</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_help__common__messaging__reconnect\">frame_help__common__messaging__reconnect</string>\r\n"
	    		+ "    <string name=\"frame_help__frame_my_account__lock\">frame_help__frame_my_account__lock</string>\r\n"
	    		+ "    <string name=\"frame_help__frame_my_account_login_skip_help_include\">El vocablo latino paragraphus se transformó en párrafo, un término de uso habitual en el ámbito de la gramática. Se trata de los diferentes fragmentos de un texto, que pueden reconocerse por su mayúscula al comenzar y por el punto y aparte que marca su final.\\r\\n \\r\\n Un párrafo puede estar formado por una o más oraciones. Cada una de ellas se encuentra separada de la otra a través de un punto y seguido. Las oraciones, a su vez, son conjuntos de palabras que componen una unidad de sentido. Si seguimos desmenuzando los elementos, también podemos afirmar que las palabras se crean a partir de la combinación de letras.</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__my_message_error_not_send\">item_list_view_message_detail__state__my_message_error_not_send</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__message_sent\">item_list_view_message_detail__state__message_sent</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__message_sending\">item_list_view_message_detail__state__message_sending</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_server\">item_list_view_message_detail__state__destiny_server</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_delivered\">item_list_view_message_detail__state__destiny_delivered</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_read_hidden\">item_list_view_message_detail__state__destiny_read_hidden</string>\r\n"
	    		+ "    <string name=\"item_list_view_message_detail__state__destiny_read\">item_list_view_message_detail__state__destiny_read</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__anonimo\">Es un mensaje con envío Anónimo</string>\r\n"
	    		+ "    <string name=\"message_detail__icon__block_download\">Descarga Bloqueada</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__random_nickname\">message_detail__icon__random_nickname</string>\r\n"
	    		+ "    <string name=\"message_detail__icon__is_audio_message\">Es un mensaje de audio</string>\r\n"
	    		+ "    <string name=\"message_detail__icon__is_hide_message_read_state\">message_detail__icon__is_hide_message_read_state</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_time\">Es un mensaje Temporal</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__has_image\">Contiene una Imagen</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_resend\">Es un mensaje Reenviado</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_reply\">Es una respuesta a otro mensaje</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_extra_encrypt\">Tiene Extra Encriptación</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__block_resend_true\">Mensaje con Bloqueo de Reenvío</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__is_black\">Es un mensaje en Modo Black</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"message_detail__icon__block_resend_false\">Mensaje sin Bloqueo de Reenvío</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__allow_audio_txt\">Bloquear mensajes de Audio</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_text_resize__max_size\">Tamaño máximo</string>\r\n"
	    		+ "    <string name=\"frame_text_resize__min_size\">Tamaño mínimo</string>\r\n"
	    		+ "    <string name=\"general__password\">Contraseña</string>\r\n"
	    		+ "    <string name=\"general__role\">Rol</string>\r\n"
	    		+ "    <string name=\"menu_message__empty_list\">Vaciar Mensajes</string>\r\n"
	    		+ "    <string name=\"menu_message__get_historial\">Cargar 10 Mensajes Anteriores</string>\r\n"
	    		+ "    <string name=\"menu_message__add_member\">Agregar Contacto al Grupo</string>\r\n"
	    		+ "    <string name=\"menu_message__grupo_info\">Información del Grupo</string>\r\n"
	    		+ "    <string name=\"general__actual_password\">Actual contraseña</string>\r\n"
	    		+ "    <string name=\"general__new_password\"> </string>\r\n"
	    		+ "    <string name=\"general__password_confirmar\">Confirmación</string>\r\n"
	    		+ "    <string name=\"general__save\">Guardar</string>\r\n"
	    		+ "    <string name=\"general__save_close\">Guardar y Cerrar</string>\r\n"
	    		+ "    <string name=\"general__confirm\">Confirmar</string>\r\n"
	    		+ "    <string name=\"general__are_u_sure\">¿Estás Seguro?</string>\r\n"
	    		+ "    <string name=\"general__cancel\">Cancelar</string>\r\n"
	    		+ "    <string name=\"general__accept\">Aceptar</string>\r\n"
	    		+ "    <string name=\"general__example\">Example Exemple Ejemplo Exemplo приклад</string>\r\n"
	    		+ "    <string name=\"general__log\">Detalles</string>\r\n"
	    		+ "    <string name=\"general__reset\">Reestablecer</string>\r\n"
	    		+ "    <string name=\"general__ignore\">Ignorar</string>\r\n"
	    		+ "    <string name=\"general__saved\">Guardado</string>\r\n"
	    		+ "    <string name=\"general__share\">Compartir</string>\r\n"
	    		+ "    <string name=\"general__available\">Disponible</string>\r\n"
	    		+ "    <string name=\"general__not_available\">No disponible</string>\r\n"
	    		+ "    <string name=\"general__recomendado\">Recomendado</string>\r\n"
	    		+ "    <string name=\"general__default\">Reestablecer</string>\r\n"
	    		+ "    <string name=\"general__error_ph1\">Error: %1$s</string>\r\n"
	    		+ "    <string name=\"general__error__no_description\">código: %1$s - sin descripción</string>\r\n"
	    		+ "    <string name=\"general__error_message\">Mensaje de Error</string>\r\n"
	    		+ "    <string name=\"general__error_message_ph1\">Mensaje de Error: %1$s</string>\r\n"
	    		+ "    <string name=\"general__error__call_rest__title\">Error llamando al Servidor: %1$s</string>\r\n"
	    		+ "    <string name=\"general__roles__admin\">Administrador</string>\r\n"
	    		+ "    <string name=\"general__roles__moderator\">Moderador</string>\r\n"
	    		+ "    <string name=\"general__save__not_changes\">No hay modificaciones que guardar</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lang__title\">Idioma y Visualización</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"general__roles__member\">Miembro</string>\r\n"
	    		+ "    <string name=\"general__roles__readonly\">Solo Lectura</string>\r\n"
	    		+ "    <string name=\"general__message_type__anonimous\">Anónimo</string>\r\n"
	    		+ "    <string name=\"general__message_type__temporal\">Temporal</string>\r\n"
	    		+ "    <string name=\"general__message_type__black\">Black</string>\r\n"
	    		+ "    <string name=\"general__message_type__extra_encriptado\">Extra Encriptado</string>\r\n"
	    		+ "    <string name=\"general__alert__validation__password_incorrect\">Contraseña Incorrecto</string>\r\n"
	    		+ "    <string name=\"general__alert__validation__role__only_admin\">Esta pantalla es solo para Administradores. Su rol es %1$s</string>\r\n"
	    		+ "    <string name=\"general__message_status__my_message_error_not_send\">Error</string>\r\n"
	    		+ "    <string name=\"general__message_status__my_message_sending\">Enviando</string>\r\n"
	    		+ "    <string name=\"general__message_status__my_message_sent\">Enviado</string>\r\n"
	    		+ "    <string name=\"general__message_status__destiny_server\">Servidor</string>\r\n"
	    		+ "    <string name=\"general__message_status__destiny_delivered\">Entregado</string>\r\n"
	    		+ "    <string name=\"general__message_status__destiny_readed\">Leído</string>\r\n"
	    		+ "    <string name=\"dialog_to_show__alert__validation_by_role\">Acción no permitida. Su rol en el grupo es %1$s</string>\r\n"
	    		+ "    <string name=\"copy_paste_util__no_data_to_copy\">No hay datos que copiar</string>\r\n"
	    		+ "    <string name=\"copy_paste_util__copied\">Copiado</string>\r\n"
	    		+ "    <string name=\"copy_paste_util__copy\">Copiar</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__create_grupo\">Crear Grupo</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__invitation_code\">Código de Invitación</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__my_account\">Mi cuenta</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__about_this\">Acerca de</string>\r\n"
	    		+ "    <string name=\"menu_grupo__item__exit\">Salir</string>\r\n"
	    		+ "    <string name=\"accept_invitation_callrest__invitation_accepted\">Invitación Aceptada</string>\r\n"
	    		+ "    <string name=\"grupo_info_activity__title\">Información Grupo: %1$s</string>\r\n"
	    		+ "    <string name=\"grupo_info_activity__remove_me__success\">Has dejado el grupo</string>\r\n"
	    		+ "    <string name=\"grupo_info_activity__delete_grupo__success\">Grupo eliminado</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__bloqueo_remoto__title\">Bloque Remoto</string>\r\n"
	    		+ "    <string name=\"general__enter_password__for_action\">Ingrese su contraseña para realizar esta acción</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__members__title\">Integrantes</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__members__add_member\">Agregar nuevo Integrante</string>\r\n"
	    		+ "    <string name=\"message_activity__envio_especial__title\">Envío Especial</string>\r\n"
	    		+ "    <string name=\"message_activity__delete_message__for_me\">Eliminar para Mi</string>\r\n"
	    		+ "    <string name=\"message_activity__delete_message__for_everyone\">Eliminar para todos</string>\r\n"
	    		+ "    <string name=\"message_activity__delete_message__for_everyone_and_resend\">Eliminar para todos y reenvíos</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__delete\">Eliminar</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__forward\">Reenviar</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__response\">Responder</string>\r\n"
	    		+ "    <string name=\"message_activity_message_actions__reintentar\">Reintentar</string>\r\n"
	    		+ "    <string name=\"message_activity_audio__error__init\">No se pudo inicializar AudioTrack, verifique la configuración</string>\r\n"
	    		+ "    <string name=\"message_activity__extra_encrypt__delete__question\">¿Desea Borrar la Extra Encrypt Key?</string>\r\n"
	    		+ "    <string name=\"message_activity__extra_encrypt__add_key\">Ingrese Extra Encrypt Key</string>\r\n"
	    		+ "    <string name=\"message_resend_activity__title\">Reenviar</string>\r\n"
	    		+ "    <string name=\"message_resend_activity__resend__sucess\">Mensaje/s Reenviado</string>\r\n"
	    		+ "    <string name=\"message_resend_activity__resend__fail\">Error al Reenviar</string>\r\n"
	    		+ "    <string name=\"main_login__registrarse\">Registrarse</string>\r\n"
	    		+ "    <string name=\"main_login__ingresar\">Ingresar</string>\r\n"
	    		+ "    <string name=\"main_login__usuario\">Usuario</string>\r\n"
	    		+ "    <string name=\"main_login__password\">Contraseña</string>\r\n"
	    		+ "    <string name=\"main_login__alert__sin_internet__title\">Sin Internet</string>\r\n"
	    		+ "    <string name=\"main_login__alert__sin_internet__detail\">Verifique su conexión a internet.</string>\r\n"
	    		+ "    <string name=\"main_login__validate_password__empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"main_login__validate_usuario__empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"main_login__title\">Privacity</string>\r\n"
	    		+ "    <string name=\"main_login__alert__servidor_no_responde__title\">El servidor configurado no responde</string>\r\n"
	    		+ "    <string name=\"main_login__alert__servidor_no_responde___detail\">Verifique la configuración</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"main_login__alert__alert__error_rest__title\">ERROR</string>\r\n"
	    		+ "    <string name=\"main_login__alert__alert__error_rest__detail\">Ejecutando Rest: %1$s</string>\r\n"
	    		+ "    <string name=\"main_login__menu__item__configuration\">Configuración</string>\r\n"
	    		+ "    <string name=\"main_login__menu__item__espanol\">Español</string>\r\n"
	    		+ "    <string name=\"main_login__menu__item__english\">English</string>\r\n"
	    		+ "    <string name=\"main_login__version\">Versión %1$s</string>\r\n"
	    		+ "    <string name=\"lock_activity__bloqueo_remoto_mensaje\">Algún grupo ha enviado un bloqueo remoto</string>\r\n"
	    		+ "    <string name=\"register_activity__usuario\">Usuario</string>\r\n"
	    		+ "    <string name=\"register_activity__password\">Contraseña</string>\r\n"
	    		+ "    <string name=\"register_activity__password_confirmar\">Confirmar</string>\r\n"
	    		+ "    <string name=\"register_activity__requerido\">* Requerido</string>\r\n"
	    		+ "    <string name=\"register_activity__submit\">CREAR CUENTA</string>\r\n"
	    		+ "    <string name=\"register_activity__submit__procesando\">Procesando</string>\r\n"
	    		+ "    <string name=\"registro_title\">Registración</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_empty\">El usuario no puede estar vacío</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_too_short\">El usuario debe tener al menos %1$ caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_too_long\">El usuario debe tener máximo %1$ caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_nickname_empty\">El nickname no puede estar vacío</string>\r\n"
	    		+ "    <string name=\"registro_validation_nickname_too_long\">El nickname debe tener máximo %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_exists\">El nombre de usuario ya está utilizado</string>\r\n"
	    		+ "    <string name=\"registro_validation_user_ok\">El nombre de usuario es válido</string>\r\n"
	    		+ "    <string name=\"registro_validation_error\">Hay error/es en la validación</string>\r\n"
	    		+ "    <string name=\"registro_validation_password2_no_change\">Debe ser diferente al actual</string>\r\n"
	    		+ "    <string name=\"registro_validation_password2\">Las contraseñas son diferentes</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_too_short\">Debe tener al menos %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_too_short\">Podría tener al menos %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_too_long\">Debe tener al máximo %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_white_space\">No puede contener espacios en blanco</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_contains_white_space\">Podría no contener espacios en blanco</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_special\">Debe tener al menos %1$s carácter especial</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_specials\">Debe tener al menos %1$s caracteres especiales</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_special\">Tener al menos %1$s carácter especial</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_specials\">Tener al menos %1$s caracteres especiales</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia\">Sugerencia:</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_muy_seguro\">Muy Seguro</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_mayuscula\">Debe tener al menos %1$s mayúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_mayusculas\">Debe tener al menos %1$s mayúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_mayuscula\">Tener al menos %1$s mayúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_mayusculas\">Tener al menos %1$s mayúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_minuscula\">Debe tener al menos %1$s minúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_minusculas\">Debe tener al menos %1$s minúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_minuscula\">Tener al menos %1$s minúscula</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_minusculas\">Tener al menos %1$s minúsculas</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_numero\">Debe tener al menos %1$s número</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_numeros\">Debe tener al menos %1$s números</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_numero\">Tener al menos %1$s número</string>\r\n"
	    		+ "    <string name=\"registro_validation_sugerencia_password1_must_contains_numeros\">Tener al menos %1$s números</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_ilegal_match\">No puede tener %1$s caracteres consecutivos</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_must_contains_sugerencia_ilegal_match\">Podría no tener %1$s caracteres consecutivos</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_usuario\">El usuario no puede estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_sugerencia_usuario\">El usuario podría no estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_nickname\">El nickname no puede estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_sugerencia_nickname\">El nickname podría no estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_password\">La contraseña no puede estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_contains_sugerencia_password\">La contraseña podría no estar presente</string>\r\n"
	    		+ "    <string name=\"registro_validation_password1_ok\">La contraseña es válida</string>\r\n"
	    		+ "    <string name=\"registro_validation_password2_ok\">Las contraseñas son correctas</string>\r\n"
	    		+ "    <string name=\"registro_nickname_notification\">Si se deja vacío se generará uno de forma aleatoria - Luego se puede cambiar.</string>\r\n"
	    		+ "    <string name=\"registro_user_created\">El Usuario fue Creado</string>\r\n"
	    		+ "    <string name=\"password_old_new_equals\">La contraseña Nueva debe ser diferente al Actual</string>\r\n"
	    		+ "    <string name=\"password_validation__TOO_SHORT\">Debe tener al menos %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"password_validation__TOO_LONG\">Debe tener al menos  %1$s caracteres</string>\r\n"
	    		+ "    <string name=\"addmember_activity__invitation_message__validate__caracteres_disponibles\">Caracteres disponibles %1$s.</string>\r\n"
	    		+ "    <string name=\"addmember_activity__invitation_code__validate__empty\">El código de invitación no puede estar vacío</string>\r\n"
	    		+ "    <string name=\"addmember_activity__send_invitation__success\">El Usuario ha sido Invitado</string>\r\n"
	    		+ "    <string name=\"grupo_activity__title\">Privacity - Grupos</string>\r\n"
	    		+ "    <string name=\"grupo_activity__query_hint\">Buscar título</string>\r\n"
	    		+ "    <string name=\"grupo_activity__powerservice__title\">SOLICITUD DE PERMISO</string>\r\n"
	    		+ "    <string name=\"grupo_activity__powerservice__detail\">En la siguiente pantalla se le solicitara permisos para poder continuar recibiendo mensajes cuando el móvil entre en modo reposo. La aplicación utiliza su propia recepción de mensajes, por seguridad descarta soluciones de terceros como las proporcionadas por Google. Garantizamos que no afectará en consumo de la batería, ni del consumo de datos más de lo estrictamente necesario.\\nSi acepta puede cambiar la configuración en cualquier momento. Si no acepta seguirá funcionando, pero en Modo Reposo no recibirá notificación alguna.</string>\r\n"
	    		+ "    <string name=\"grupo_activity__exit__cerrar_app\">Cerrar App</string>\r\n"
	    		+ "    <string name=\"grupo_activity__exit__cerrar_session\">Cerrar Sesión</string>\r\n"
	    		+ "    <string name=\"grupo_activity__exit__minimizar\">Minimizar</string>\r\n"
	    		+ "    <string name=\"grupo_activity__members__online__title\">Miembros</string>\r\n"
	    		+ "    <string name=\"grupo_activity__members__online__detail\">Conectados: %1$s de %2$s</string>\r\n"
	    		+ "    <string name=\"grupo_activity__invitation__response\">Responder a la solicitud</string>\r\n"
	    		+ "    <string name=\"grupo_activity__invitation__response_details1\">Ha sido invitado por %1$s</string>\r\n"
	    		+ "    <string name=\"grupo_activity__invitation__response_details2\">Con el rol de  %1$s</string>\r\n"
	    		+ "    <string name=\"imagefull_activity__title\">Visor de Imagen</string>\r\n"
	    		+ "    <string name=\"imagefull_activity__validation__download__not_allowed\">La configuración del Mensaje no permite la descarga</string>\r\n"
	    		+ "    <string name=\"imagefull_activity__validation__download__success\">Archivo Descargado</string>\r\n"
	    		+ "    <string name=\"lock_activity__validation__password__fail\">Contraseña Incorrecta\\nIntento %1$s de %2$s</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__title\">Privacity - Crear Grupo</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__grupo_created\">GRUPO CREADO</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__alert__error_encrypt_title\">ERROR ENCRIPTACION</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__submit\">Crear</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__add_new_member\">Agregar un Integrante</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__goto_grupoinfo\">Información del Grupo</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__create_another_grupo\">crear nuevo grupo</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__go_back\">Volver</string>\r\n"
	    		+ "    <string name=\"addgrupo_activity__name_grupo__hint\">Nombre del Nuevo Grupo</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__generate_and_save\">Generar Nuevo y Guardar</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__title\">Código de Invitación</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__reset\">Reestablecer</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__save\">Guardar</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__codigo_sin_cambios\">Código sin cambios</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__codigo_validate__empty\">No puede estar vacío</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__codigo_validate__no_save\">Debe Guardar o restablecer para compartir</string>\r\n"
	    		+ "    <string name=\"acodigoinvitacion_activity__alert__error_generated_title\">Error generando Código de Invitación</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__save__ok\">Guardado</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__share__message__body\">Mi código de invitación es: %1$s</string>\r\n"
	    		+ "    <string name=\"codigoinvitacion_activity__share__message__extra_subject\">Únete a la app de mensajería más segura del mundo</string>\r\n"
	    		+ "    <string name=\"grupo_info__lock_title\">Contraseña y Bloqueo</string>\r\n"
	    		+ "    <string name=\"grupo_info_password_enabled\">Contraseña Activado</string>\r\n"
	    		+ "    <string name=\"grupo_info_lock_enabled\">Cerrar la conversación</string>\r\n"
	    		+ "    <string name=\"grupo_info_lock__detail_message\">La contraseña esta activo en la aplicación solamente. Si desea más seguridad incluya un Extra Encrypt.</string>\r\n"
	    		+ "    <string name=\"mainconfiguracion_activity__validation__error__url\">URL invalida</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__desconexiones\">Desconexiones:</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__reintentos_total\">Reintentos Total:</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__intentar_reconecta_en\">Intentar reconectar en</string>\r\n"
	    		+ "    <string name=\"general__segundos\">segundos</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__reconnet_trying\">reconexión - reintentando...</string>\r\n"
	    		+ "    <string name=\"my_account_conf_descarga_imagen_txt\">Bloquear la Descarga de las Imagenes y Videos de mis envios</string>\r\n"
	    		+ "    <string name=\"my_account_conf_gen_ocultar_estado_txt\">Ocultar la Lectura de los Mensajes Recibidos</string>\r\n"
	    		+ "    <string name=\"my_account_conf__block_resend__txt\">Bloquear el Reenvío de Mis Mensajes</string>\r\n"
	    		+ "    <string name=\"my_account_conf_temporal_obligatorio_txt\">Enviar Siempre Mensajes Temporales</string>\r\n"
	    		+ "    <string name=\"my_account_conf_temporal_maximo_tiempo_permitido_titulo\">Tiempo</string>\r\n"
	    		+ "    <string name=\"my_account_conf_black_obligatorio_adjunto_txt\">Enviar Siempre Imágenes y Videos en modo Black</string>\r\n"
	    		+ "    <string name=\"my_account_conf_black_obligatorio_adjunto_recibido_txt\">Recibir Siempre Imágenes y Videos en modo Black</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"my_account_activity__title\">Mi cuenta</string>\r\n"
	    		+ "    <string name=\"frame_reconnect__server_disconnectad\">Desconectado del servidor</string>\r\n"
	    		+ "    <string name=\"frame_my_account__password_title\">Cambiar Contraseña</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info_nickname__generator\">Generar un Nickname Aleatorio</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info_nickname__message_info\">Si se deja en blanco se usará el Nickname General que actualmente es: %1$s</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info_nickname__title\">NICKNAME PARA TU USUARIO</string>\r\n"
	    		+ "    <string name=\"message_activity__allow_audio__not_allow\">La configuración del grupo no permite enviar mensajes de audio</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__audio_max_time\">Tiempo Máximo</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__random_nickname_txt\">Usar Nickname Aleatorio para todos los integrantes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__hide_member_list_txt\">Ocultar Lista de Integrantes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__hide_message_read_state_txt\">Ocultar Estado Leído de los Mensajes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__hide_message_details_txt\">Ocultar Detalles de los Mensajes</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__black_message_attach_mandatory_txt\">Modo Black Obligatorio cuando contenga Imágenes y/o Videosk</string>\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__block_resend_txt\">Bloquear reenvio</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"grupo_info_conf_gen__title\">CONFIGURACIONES GENERALES</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__name_title\">Configuración Personal</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__name_personal__title\">Configuración Personal</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__accept_and_send\">Aceptar e\\nInvitar a alguien más</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__accept_and_close\">Aceptar y Cerrar</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__add_message_invitation\">Agrega un mensaje para tu invitado</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__codigo_invitation__hint\">Código de Invitación</string>\r\n"
	    		+ "    <string name=\"activity__add_members_to_grupo__codigo_invitation__scan_qr\">Escanear QR</string>\r\n"
	    		+ "    <string name=\"frame_my_account_gral_conf_title\">CONFIGURACIONES GENERALES</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock_activar\">Bloqueo Activado</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock_validate_min_seconds\">Debe tener al menos %1$s segundos</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock_mensaje\">Si activa esta opción a la cantidad de minutos establecidos se mostrará una pantalla de bloqueo en donde habría de escribir nuevamente la contraseña.</string>\r\n"
	    		+ "    <string name=\"frame_my_account_lock\">Bloqueo de la App</string>\r\n"
	    		+ "    <string name=\"frame_my_account_login_skip__activar\">Saltar Autentificación Activado</string>\r\n"
	    		+ "    <string name=\"frame_my_account_nickname__generator\">Generar un Nickname Aleatorio</string>\r\n"
	    		+ "    <string name=\"frame_my_account_nickname__title\">NICKNAME PARA TU USUARIO</string>\r\n"
	    		+ "    <string name=\"frame_my_account_loguin_skip__title\">Saltar pantalla de ingreso</string>\r\n"
	    		+ "    <string name=\"message_detail_activity__hide_read_message\">Se oculta a los miembros del grupo que has leído este mensaje</string>\r\n"
	    		+ "    <string name=\"message_detail__hide_state_grupo_txt\">El grupo está configurado para ocultar el estado de todos los mensajes, solo tú puedes ver el estado de tu actividad</string>\r\n"
	    		+ "    <string name=\"message_detail_activity__title\">Privacity – Detalles del Mensaje</string>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"frame_grupo_info__member__title\">Integrantes</string>\r\n"
	    		+ "    <string name=\"frame_grupo_info__hide_member__admin_message_txt\">El grupo está configurado para que unicamente el Administrador pueda ver la lista completa de Integrantes</string>\r\n"
	    		+ "    <string name=\"privacity_environment\">General</string>\r\n"
	    		+ "    <string name=\"app_name\">Privacity</string>\r\n"
	    		+ "    <string name=\"error_codigo\">ERROR CÓDIGO</string>\r\n"
	    		+ "    <string name=\"ok\">OK</string>\r\n"
	    		+ "    <string name=\"close\">Cerrar</string>\r\n"
	    		+ "    <string name=\"cancel\">Cancelar</string>\r\n"
	    		+ "    <string name=\"error_code__CL_V_1001\">EL CAMPO DE VALIDACIÓN DEL CLIENTE ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__GI_000\">GENERAL INESPERADO</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1000\">GENERAL ACCESO INVÁLIDO</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1001\">GENERAL NO GUARDAR PORQUE NO HAY CAMBIOS DE DATOS</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1002\">GENERAL SIN ACCESO A INTERNET</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1003\">GENERAL PROTOCOLO DE ACCESO INVÁLIDO</string>\r\n"
	    		+ "    <string name=\"error_code__GRAL_1004\">GENERAL DATOS ENVIADOS INVÁLIDOS</string>\r\n"
	    		+ "    <string name=\"error_code__G_1000\">EL GRUPO USUARIO NO EXISTE CÓDIGO DE INVITACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__G_1001\">EL GRUPO USUARIO ESTÁ EN EL GRUPO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1002\">EL GRUPO ID DE GRUPO MAL FORMATO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1003\">EL GRUPO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__G_1004\">EL GRUPO USUARIO NO ESTÁ EN EL GRUPO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1005\">EL GRUPO USUARIO NO TIENE PERMISO EN ESTE GRUPO PARA AGREGAR MIEMBROS</string>\r\n"
	    		+ "    <string name=\"error_code__G_1006\">EL ROL DE GRUPO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__G_1007\">EL CÓDIGO DE INVITACIÓN DE USUARIO DE GRUPO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__G_1008\">LA INVITACIÓN DE GRUPO EXISTE INVITACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__G_1009\">LA INVITACIÓN DE USUARIO DE GRUPO NO PUEDE SER LA MISMA</string>\r\n"
	    		+ "    <string name=\"error_code__G_1010\">EL GRUPO USUARIO NO PUEDE ENVIAR MENSAJE</string>\r\n"
	    		+ "    <string name=\"error_code__G_1011\">EL GRUPO USUARIO NO PUEDE ENVIAR MENSAJE DE SÓLO LECTURA</string>\r\n"
	    		+ "    <string name=\"error_code__G_1012\">GRUPO GENERAL CONF LOCK MIN SEGUNDOS VALIDACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__G_1013\">ROL GRUPO NO PERMITIR ESTA ACCIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1000\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA ANTERIOR ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1001\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA NUEVA ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1002\">CAMBIAR CONTRASEÑA VALIDACIÓN CONFIRMAR CONTRASEÑA NUEVA ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1003\">CAMBIAR CONTRASEÑA VALIDACIÓN NUEVA CONTRASEÑA ES DIFERENTE NUEVA CONFIRMAR CONTRASEÑA</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1004\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA ANTERIOR INCORRECTA</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1005\">CAMBIAR CONTRASEÑA VALIDACIÓN NUEVA CONTRASEÑA ES IGUAL CONTRASEÑA ANTERIOR</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1008\">CAMBIAR CONTRASEÑA VALIDACIÓN CONTRASEÑA ANTERIOR ES DIFERENTE A LA CONTRASEÑA REGISTRADA</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_1006\">CAMBIAR CONTRASEÑA VALIDACIÓN NOMBRE USUARIO INCORRECTO</string>\r\n"
	    		+ "    <string name=\"error_code__CPWV_10007\">CAMBIAR CONTRASEÑA VALIDACIÓN NOMBRE USUARIO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__Z_1001\">COMPRIMIR ZIP</string>\r\n"
	    		+ "    <string name=\"error_code__Z_1002\">DESCOMPRIMIR ZIP</string>\r\n"
	    		+ "    <string name=\"error_code__DC_1001\">CONVERTIR BYTES DATOS A CADENA</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1000\">LONGITUD INCORRECTA ID DE PETICIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1001\">ID DE PETICIÓN NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1002\">ID DE SOLICITUD EXPIRÁ</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1003\">ID DE SOLICITUD NO PUEDE SER NULO</string>\r\n"
	    		+ "    <string name=\"error_code__RI_1004\">ID DE SOLICITUD NO PUEDE USARSE VARIAS VECES</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"error_code__U_1000\">EL SISTEMA DE USUARIO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__U_1001\">EL USUARIO NO REGISTRA DEL USUARIO</string>\r\n"
	    		+ "    <string name=\"error_code__U_1002\">EL APODEMOS DE USUARIO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__U_1003\">NOMBRE DE USUARIO DEMASIADO LARGO</string>\r\n"
	    		+ "    <string name=\"error_code__U_1004\">NOMBRE DE USUARIO DEMASIADO CORT0</string>\r\n"
	    		+ "    <string name=\"error_code__U_1005\">USUARIO NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__A_1000\">NOMBRE DE USUARIO AUTORIZADO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__A_1001\">NOMBRE DE USUARIO AUTORIZADO ES NULO</string>\r\n"
	    		+ "    <string name=\"error_code__A_1002\">NOMBRE DE USUARIO AUTORIZADO ES DEMASIADO CORT0</string>\r\n"
	    		+ "    <string name=\"error_code__A_1003\">El Usuario y/o Contraseña\\n son Inválidos</string>\r\n"
	    		+ "    <string name=\"error_code__recomendacion__A_1003\">Verifique los datos y vuelva a intentarlo</string>\r\n"
	    		+ "\r\n"
	    		+ "    <string name=\"error_code__RI_1005\">El Servidor está en Mantenimiento</string>\r\n"
	    		+ "    <string name=\"error_code__recomendacion__RI_1005\">Vuelva a intentarlo en un unos minutos</string>\r\n"
	    		+ "    <string name=\"error_code__A_1004\">SESIÓN DE AUTENTICACIÓN FUERA DE SINCRONIZACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__A1005\">FALLO DE OBTENCIÓN DE TOKEN DE AUTENTICACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__M_1000\">MENSAJE ID MENSAJE MAL FORMATO</string>\r\n"
	    		+ "    <string name=\"error_code__M_1001\">MENSAJE NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__M_1002\">MENSAJE NO CREADOR MENSAJE</string>\r\n"
	    		+ "    <string name=\"error_code__MDD_1001\">MEDIADATA NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1000\">DETALLE MENSAJE ID DETALLE MENSAJE MAL FORMATO</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1001\">DETALLE MENSAJE NO EXISTE</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1002\">DETALLE DEL MENSAJE ELIMINADO</string>\r\n"
	    		+ "    <string name=\"error_code__MD_1003\">DETALLE DEL MENSAJE NO EXISTE HORA DEL MENSAJE</string>\r\n"
	    		+ "    <string name=\"error_code__MY_1000\">CÓDIGO DE INVITACIÓN DE MI CUENTA NO DISPONIBLE</string>\r\n"
	    		+ "    <string name=\"error_code__MY_1001\">CÓDIGO DE INVITACIÓN DE MI CUENTA NO PUEDE ESTAR VACÍO</string>\r\n"
	    		+ "    <string name=\"error_code__MY_1002\">VALIDACIÓN DE SEGUNDOS DE BLOQUEO DE MI CUENTA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1000\">ENCRYPT IS NULL</string>\r\n"
	    		+ "    <string name=\"error_code__E_1001\">LA CLAVE PRIVADA DE ENCRIPTACIÓN ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1002\">LA CLAVE PÚBLICA DE ENCRIPTACIÓN ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1003\">LA CLAVE PÚBLICA DE ENCRIPTACIÓN NO ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__E_1006\">LA INVITACIÓN DE CLAVE PÚBLICA DE ENCRIPTACIÓN DEBE SER NULA</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1001\">PROCESO DE ENCRIPTACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__DP_1001\">PROCESO DE DESENCRIPTACIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1003\">LA AES DE ENCRIPTACIÓN ES NULA</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1004\">LA CLAVE SECRETA DE ENCRYPT AES ES NULL</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1005\">LA SAL DE ENCRYPT AES ES NULL</string>\r\n"
	    		+ "    <string name=\"error_code__EA_1007\">FALLO DE CREACIÓN DE ENCRYPT AES</string>\r\n"
	    		+ "    <string name=\"error_code__DID_1001\">FALLO DE PROCESO DE DESCRYPT ID</string>\r\n"
	    		+ "    <string name=\"error_code__EID_1001\">FALLO DE PROCESO DE ENCRYPT ID</string>\r\n"
	    		+ "    <string name=\"error_code__WE_1001\">MENSAJERÍA SIN CONEXIÓN</string>\r\n"
	    		+ "    <string name=\"error_code__ME_1002\">PROTOCOLO DE ACCESO NO VÁLIDO DE MENSAJERÍA</string>\r\n"
	    		+ "    <string name=\"error_code__WE_1003\">ERROR AL OBTENER MIEMBROS EN LÍNEA DE MENSAJERÍA</string>\r\n"
	    		+ "    <string name=\"error_code__SM_1001\">ADMINISTRADOR DE SESIÓN DESCONECTADO</string>\r\n"
	    		+ "    <string name=\"error_code__HC_1001\">PING DEL COMPROBADOR DE ESTADO SIN RESPUESTA</string>\r\n"
	    		+ "    <string name=\"error_code__IP_1003\">ERROR GENERAL DEL PROVEEDOR DE IDS</string>\r\n"
	    		+ "    <string name=\"error_code__IP_1001\">PROVEEDOR DE IDS DESCONECTADO</string>\r\n"
	    		+ "    <string name=\"error_code__IP_1002\">NO SE DEBE INVOCAR LA ACTUALIZACIÓN DEL PROVEEDOR DE IDS EN ESTE CASO</string>\r\n"
	    		+ "    <string name=\"error_code__KL_1001\">ERROR DE BLOQUEO DE TECLAS</string>\r\n"
	    		+ "    <string name=\"error_code__KL_1002\">ERROR DE ACTUALIZACIÓN DE BLOQUEO DE TECLA</string>\r\n"
	    		+ "    <string name=\"error_code__M_1003\">El mensaje original esta configurado para bloquear su reenvio</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__ADMIN\">Un Administrador te asigno el Rol de Admin</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__READONLY\">Un Administrador te asigno el Rol de Solo Lectura</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__MODERATOR\">Un Administrador te asigno el Rol de Moderador</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__change__user_role__MEMBER\">Un Administrador te asigno el Rol de Miembro</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__bloque_de_emergencia\">Bloque de Emergencia</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__lock_config__modified\">UN ADMINISTRADOR HA MODIFICADO LA CONFIGURACION DE BLOQUEO DEL GRUPO</string>\r\n"
	    		+ "    <string name=\"system__message__grupo__general_config__modified\">UN ADMINISTRADOR HA MODIFICADO LA CONFIGURACION GENERAL DEL GRUPO</string>\r\n"
	    		+ "</resources>";
	            

	   String traduccion="If the problem persists, please report it @\r\n"
	   		+ "On @\r\n"
	   		+ "Off @\r\n"
	   		+ "Not Configured @\r\n"
	   		+ "Allowed @\r\n"
	   		+ "Blocked @\r\n"
	   		+ "Required @\r\n"
	   		+ "frame_help__common__messaging__reconnect @\r\n"
	   		+ "frame_help__frame_my_account__lock @\r\n"
	   		+ "The Latin word paragraphus became paragraph, a term commonly used in grammar. It refers to the different fragments of a text, which can be recognized by the capital letter at the beginning and the period at the end. A paragraph can be made up of one or more sentences. Each sentence is separated from the next by a period. Sentences, in turn, are sets of words that make up a unit of meaning. If we continue to break down the elements, we can also say that words are created from the combination of letters. @\r\n"
	   		+ "item_list_view_message_detail__state__my_message_error_not_send @\r\n"
	   		+ "item_list_view_message_detail__state__message_sent @\r\n"
	   		+ "item_list_view_message_detail__state__message_sending @\r\n"
	   		+ "item_list_view_message_detail__state__destiny_server @\r\n"
	   		+ "item_list_view_message_detail__state__destiny_delivered @\r\n"
	   		+ "item_list_view_message_detail__state__destiny_read_hidden @\r\n"
	   		+ "item_list_view_message_detail__state__destiny_read @\r\n"
	   		+ "It is a message sent Anonymous @\r\n"
	   		+ "Download Blocked @\r\n"
	   		+ "message_detail__icon__random_nickname @\r\n"
	   		+ "It is an audio message @\r\n"
	   		+ "message_detail__icon__is_hide_message_read_state @\r\n"
	   		+ "It's a message Temporary @\r\n"
	   		+ "Contains an Image @\r\n"
	   		+ "Is a Forwarded Message @\r\n"
	   		+ "Is a Reply to Another Message @\r\n"
	   		+ "Has Extra Encryption @\r\n"
	   		+ "Message with Forwarding Lock @\r\n"
	   		+ "Is a Message in Black Mode @\r\n"
	   		+ "Message without Forwarding Lock @\r\n"
	   		+ "Block Audio Messages @\r\n"
	   		+ "Maximum Size @\r\n"
	   		+ "Minimum Size @\r\n"
	   		+ "Password @\r\n"
	   		+ "Role @\r\n"
	   		+ "Clear Messages @\r\n"
	   		+ "Load 10 Previous Messages @\r\n"
	   		+ "Add Contact to Group @\r\n"
	   		+ "Group Information @\r\n"
	   		+ "Current Password @\r\n"
	   		+ "New Password @\r\n"
	   		+ "Confirmation @\r\n"
	   		+ "Save @\r\n"
	   		+ "Save & Close @\r\n"
	   		+ "Confirm @\r\n"
	   		+ "Are You Sure? @\r\n"
	   		+ "Cancel @\r\n"
	   		+ "OK @\r\n"
	   		+ "Example Example Example Example @\r\n"
	   		+ "Details @\r\n"
	   		+ "Reset @\r\n"
	   		+ "Ignore @\r\n"
	   		+ "Saved @\r\n"
	   		+ "Share @\r\n"
	   		+ "Available @\r\n"
	   		+ "Not available @\r\n"
	   		+ "Recommended @\r\n"
	   		+ "Reset @\r\n"
	   		+ "Error: %1$s @\r\n"
	   		+ "code: %1$s - no description @\r\n"
	   		+ "Error Message @\r\n"
	   		+ "Error Message: %1$s @\r\n"
	   		+ "Error calling Server: %1$s @\r\n"
	   		+ "Administrator @\r\n"
	   		+ "Moderator @\r\n"
	   		+ "No changes to save @\r\n"
	   		+ "Language & Display @\r\n"
	   		+ "Member @\r\n"
	   		+ "Read Only @\r\n"
	   		+ "Anonymous @\r\n"
	   		+ "Temporary @\r\n"
	   		+ "Black @\r\n"
	   		+ "Extra Encrypted @\r\n"
	   		+ "Incorrect Password @\r\n"
	   		+ "This screen is for Administrators only. Your role is %1$s @\r\n"
	   		+ "Error @\r\n"
	   		+ "Sending @\r\n"
	   		+ "Sent @\r\n"
	   		+ "Server @\r\n"
	   		+ "Delivered @\r\n"
	   		+ "Read @\r\n"
	   		+ "Action not allowed. Your role in the group is %1$s @\r\n"
	   		+ "No data to copy @\r\n"
	   		+ "Copied @\r\n"
	   		+ "Copy @\r\n"
	   		+ "Create Group @\r\n"
	   		+ "Invitation Code @\r\n"
	   		+ "My Account @\r\n"
	   		+ "About @\r\n"
	   		+ "Leave @\r\n"
	   		+ "Invitation Accepted @\r\n"
	   		+ "Group Information: %1$s @\r\n"
	   		+ "You have left the group @\r\n"
	   		+ "Group deleted @\r\n"
	   		+ "Remote Block @\r\n"
	   		+ "Enter your password to perform this action @\r\n"
	   		+ "Members @\r\n"
	   		+ "Add New Member @\r\n"
	   		+ "Special Send @\r\n"
	   		+ "Delete for Me @\r\n"
	   		+ "Delete for Everyone @\r\n"
	   		+ "Delete for Everyone and Forwards @\r\n"
	   		+ "Delete @\r\n"
	   		+ "Forward @\r\n"
	   		+ "Reply @\r\n"
	   		+ "Retry @\r\n"
	   		+ "AudioTrack could not be initialized, please check your settings @\r\n"
	   		+ "Do you want to delete the Extra Encrypt Key? @\r\n"
	   		+ "Enter Extra Encrypt Key @\r\n"
	   		+ "Forward @\r\n"
	   		+ "Forwarded Message(s) @\r\n"
	   		+ "Forwarding Error @\r\n"
	   		+ "Register @\r\n"
	   		+ "Login @\r\n"
	   		+ "Username @\r\n"
	   		+ "Password @\r\n"
	   		+ "No Internet @\r\n"
	   		+ "Check your internet connection. @\r\n"
	   		+ "Cannot be empty @\r\n"
	   		+ "Cannot be empty @\r\n"
	   		+ "Privacy @\r\n"
	   		+ "The configured server is not responding @\r\n"
	   		+ "Check the configuration @\r\n"
	   		+ "ERROR @\r\n"
	   		+ "Running Rest: %1$s @\r\n"
	   		+ "Configuration @\r\n"
	   		+ "Spanish @\r\n"
	   		+ "English @\r\n"
	   		+ "Version %1$s @\r\n"
	   		+ "Some group has sent a remote lock @\r\n"
	   		+ "User @\r\n"
	   		+ "Password @\r\n"
	   		+ "Confirm @\r\n"
	   		+ "* Required @\r\n"
	   		+ "CREATE ACCOUNT @\r\n"
	   		+ "Processing @\r\n"
	   		+ "Registration @\r\n"
	   		+ "User cannot be empty @\r\n"
	   		+ "User must be at least %1$ characters @\r\n"
	   		+ "User must be at most %1$ characters @\r\n"
	   		+ "Nickname cannot be empty @\r\n"
	   		+ "Nickname must be at most %1$s characters @\r\n"
	   		+ "Username is already taken @\r\n"
	   		+ "Username is valid @\r\n"
	   		+ "There are errors in validation @\r\n"
	   		+ "Must be different from the current one @\r\n"
	   		+ "Passwords are different @\r\n"
	   		+ "Must be at least %1$s characters @\r\n"
	   		+ "Could be at least %1$s characters @\r\n"
	   		+ "Must be at most %1$s characters @\r\n"
	   		+ "Cannot be empty @\r\n"
	   		+ "Cannot contain spaces @\r\n"
	   		+ "May not contain spaces @\r\n"
	   		+ "Must have at least %1$s special character @\r\n"
	   		+ "Must have at least %1$s special characters @\r\n"
	   		+ "Must have at least %1$s special character @\r\n"
	   		+ "Must have at least %1$s special characters @\r\n"
	   		+ "Hint: @\r\n"
	   		+ "Very Safe @\r\n"
	   		+ "Must have at least %1$s uppercase @\r\n"
	   		+ "Must have at least %1$s uppercase @\r\n"
	   		+ "Must have at least %1$s uppercase @\r\n"
	   		+ "Must have at least %1$s uppercase @\r\n"
	   		+ "Must have at least %1$s lowercase @\r\n"
	   		+ "Must have at least %1$s lowercase @\r\n"
	   		+ "Have at least %1$s lowercase @\r\n"
	   		+ "Have at least %1$s lowercase @\r\n"
	   		+ "Must have at least %1$s number @\r\n"
	   		+ "Must have at least %1$s numbers @\r\n"
	   		+ "Have at least %1$s number @\r\n"
	   		+ "Have at least %1$s numbers @\r\n"
	   		+ "Cannot have %1$s consecutive characters @\r\n"
	   		+ "Might not have %1$s consecutive characters @\r\n"
	   		+ "The user cannot be present @\r\n"
	   		+ "The user might not be present @\r\n"
	   		+ "The nickname cannot be present @\r\n"
	   		+ "The nickname might not be present @\r\n"
	   		+ "The password cannot be present @\r\n"
	   		+ "The password might not be present @\r\n"
	   		+ "The password is valid @\r\n"
	   		+ "The passwords are correct @\r\n"
	   		+ "If left empty, a random one will be generated - It can then be changed. @\r\n"
	   		+ "The User was Created @\r\n"
	   		+ "The New Password must be different from the Current Password @\r\n"
	   		+ "Must have at least %1$s characters @\r\n"
	   		+ "Must have at least %1$s characters @\r\n"
	   		+ "Available characters %1$s. @\r\n"
	   		+ "The invitation code cannot be empty @\r\n"
	   		+ "The User has been invited @\r\n"
	   		+ "Privacy - Groups @\r\n"
	   		+ "Search title @\r\n"
	   		+ "PERMISSION REQUEST @\r\n"
	   		+ "On the next screen, you will be asked for permission to continue receiving messages when the phone goes into sleep mode. The app uses its own message reception; for security reasons, it excludes third-party solutions such as those provided by Google. We guarantee that it will not affect battery or data consumption more than strictly necessary. If you accept, you can change the settings at any time. If you do not accept, it will continue to function, but you will not receive any notifications in Sleep Mode. @\r\n"
	   		+ "Close App @\r\n"
	   		+ "Log Out @\r\n"
	   		+ "Minimize @\r\n"
	   		+ "Members @\r\n"
	   		+ "Online: %1$s of %2$s @\r\n"
	   		+ "Respond to request @\r\n"
	   		+ "You have been invited by %1$s @\r\n"
	   		+ "With the role of %1$s @\r\n"
	   		+ "Image Viewer @\r\n"
	   		+ "Message settings do not allow download @\r\n"
	   		+ "File Downloaded @\r\n"
	   		+ "Incorrect Password\\nAttempt %1$s of %2$s @\r\n"
	   		+ "Privacy - Create Group @\r\n"
	   		+ "GROUP CREATED @\r\n"
	   		+ "ENCRYPTATION ERROR @\r\n"
	   		+ "Create @\r\n"
	   		+ "Add a Member @\r\n"
	   		+ "Group Information @\r\n"
	   		+ "Create new group @\r\n"
	   		+ "Back @\r\n"
	   		+ "New Group Name @\r\n"
	   		+ "Generate New and Save @\r\n"
	   		+ "Invitation Code @\r\n"
	   		+ "Reset @\r\n"
	   		+ "Save @\r\n"
	   		+ "Code unchanged @\r\n"
	   		+ "Cannot be empty @\r\n"
	   		+ "Must Save or Reset to share @\r\n"
	   		+ "Error generating Invitation Code @\r\n"
	   		+ "Saved @\r\n"
	   		+ "My invitation code en: %1$s @\r\n"
	   		+ "Join the world's most secure messaging app @\r\n"
	   		+ "Password & Lock @\r\n"
	   		+ "Password Enabled @\r\n"
	   		+ "Close conversation @\r\n"
	   		+ "Password is enabled in the app only. If you want more security, include Extra Encrypt. @\r\n"
	   		+ "Invalid URL @\r\n"
	   		+ "Disconnections: @\r\n"
	   		+ "Total Retries: @\r\n"
	   		+ "Attempt to reconnect in @\r\n"
	   		+ "seconds @\r\n"
	   		+ "Reconnection - retrying... @\r\n"
	   		+ "Block Downloading Images and Videos from my posts @\r\n"
	   		+ "Hide Reading Received Messages @\r\n"
	   		+ "Block Forwarding My Messages @\r\n"
	   		+ "Always Send Temporary Messages @\r\n"
	   		+ "Time @\r\n"
	   		+ "Always Send Images and Videos in Black Mode @\r\n"
	   		+ "Always Receive Images and Videos in Black Mode @\r\n"
	   		+ "My Account @\r\n"
	   		+ "Disconnected from server @\r\n"
	   		+ "Change Password @\r\n"
	   		+ "Generate a Random Nickname @\r\n"
	   		+ "If left blank, the General Nickname will be used, which is currently: %1$s @\r\n"
	   		+ "NICKNAME FOR YOUR USERNAME @\r\n"
	   		+ "The group settings do not allow sending audio messages @\r\n"
	   		+ "Maximum Time @\r\n"
	   		+ "Use Random Nickname for all members @\r\n"
	   		+ "Hide Member List @\r\n"
	   		+ "Hide Read Status of Messages @\r\n"
	   		+ "Hide Message Details @\r\n"
	   		+ "Black Mode Required when containing Images and/or Videos @\r\n"
	   		+ "Block Forwarding @\r\n"
	   		+ "GENERAL SETTINGS @\r\n"
	   		+ "Personal Settings @\r\n"
	   		+ "Personal Settings @\r\n"
	   		+ "Accept and Invite someone else @\r\n"
	   		+ "Accept and Close @\r\n"
	   		+ "Add a message for your guest @\r\n"
	   		+ "Invitation Code @\r\n"
	   		+ "Scan QR @\r\n"
	   		+ "GENERAL SETTINGS @\r\n"
	   		+ "Lock Enabled @\r\n"
	   		+ "Must have at least %1$s seconds @\r\n"
	   		+ "If you enable this option within the set number of minutes, a lock screen will appear where you will have to enter your password again. @\r\n"
	   		+ "App Lock @\r\n"
	   		+ "Skip Authentication Enabled @\r\n"
	   		+ "Generate a Random Nickname @\r\n"
	   		+ "NICKNAME FOR YOUR USER @\r\n"
	   		+ "Skip Login Screen @\r\n"
	   		+ "Hide from group members that you have read this message @\r\n"
	   		+ "The group is set to hide the status of all messages, only you can see your activity status @\r\n"
	   		+ "Privacy - Message Details @\r\n"
	   		+ "Members @\r\n"
	   		+ "The group is set so that only the Admin can see the full list of Members @\r\n"
	   		+ "General @\r\n"
	   		+ "Privacy @\r\n"
	   		+ "ERROR CODE @\r\n"
	   		+ "OK @\r\n"
	   		+ "Close @\r\n"
	   		+ "Cancel @\r\n"
	   		+ "CUSTOMER VALIDATION FIELD IS NULL @\r\n"
	   		+ "GENERAL UNEXPECTED @\r\n"
	   		+ "GENERAL INVALID ACCESS @\r\n"
	   		+ "GENERAL DO NOT SAVE BECAUSE THERE ARE NO DATA CHANGES @\r\n"
	   		+ "GENERAL NO INTERNET ACCESS @\r\n"
	   		+ "GENERAL INVALID ACCESS PROTOCOL @\r\n"
	   		+ "GENERAL INVALID DATA SENT @\r\n"
	   		+ "GROUP USER INVITATION CODE DOES NOT EXIST @\r\n"
	   		+ "GROUP USER IS IN GROUP @\r\n"
	   		+ "GROUP GROUP ID IN BAD FORMAT @\r\n"
	   		+ "GROUP DOES NOT EXIST @\r\n"
	   		+ "GROUP USER IS NOT IN THE GROUP @\r\n"
	   		+ "GROUP USER DOES NOT HAVE PERMISSION IN THIS GROUP TO ADD MEMBERS @\r\n"
	   		+ "GROUP ROLE DOES NOT EXIST @\r\n"
	   		+ "GROUP USER INVITATION CODE IS NULL @\r\n"
	   		+ "GROUP INVITATION EXISTS @\r\n"
	   		+ "GROUP USER INVITATION CANNOT BE THE SAME @\r\n"
	   		+ "GROUP USER CANNOT SEND MESSAGE @\r\n"
	   		+ "GROUP USER CANNOT SEND READ-ONLY MESSAGE @\r\n"
	   		+ "GENERAL GROUP CONF LOCK MIN SECONDS VALIDATION @\r\n"
	   		+ "GROUP ROLE DO NOT ALLOW THIS ACTION @\r\n"
	   		+ "CHANGE PASSWORD VALIDATION PREVIOUS PASSWORD IS NULL @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD NEW PASSWORD IS NULL @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD CONFIRM NEW PASSWORD IS NULL @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD NEW PASSWORD IS DIFFERENT NEW CONFIRM PASSWORD @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD PREVIOUS PASSWORD IS INCORRECT @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD NEW PASSWORD IS THE SAME PREVIOUS PASSWORD @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD PREVIOUS PASSWORD IS DIFFERENT FROM THE REGISTERED PASSWORD @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD INCORRECT USERNAME @\r\n"
	   		+ "CHANGE VALIDATION PASSWORD USERNAME IS NULL @\r\n"
	   		+ "COMPRESS ZIP @\r\n"
	   		+ "UNCOMPRESS ZIP @\r\n"
	   		+ "CONVERT BYTES DATA TO STRING @\r\n"
	   		+ "INCORRECT LENGTH REQUEST ID @\r\n"
	   		+ "REQUEST ID DOES NOT EXIST @\r\n"
	   		+ "REQUEST ID WILL EXPIRE @\r\n"
	   		+ "REQUEST ID CANNOT BE NULL @\r\n"
	   		+ "REQUEST ID CANNOT BE USED MULTIPLE TIMES @\r\n"
	   		+ "USER SYSTEM DOES NOT EXIST @\r\n"
	   		+ "USER DOES NOT HAVE A USER REGISTER @\r\n"
	   		+ "USER NICKNAME IS NULL @\r\n"
	   		+ "USER NAME IS TOO LONG @\r\n"
	   		+ "USER NAME IS TOO SHORT @\r\n"
	   		+ "USER DOES NOT EXIST @\r\n"
	   		+ "AUTHORIZED USER NAME EXISTS @\r\n"
	   		+ "AUTHORIZED USER NAME IS NULL @\r\n"
	   		+ "AUTHORIZED USER NAME IS TOO SHORT @\r\n"
	   		+ "The Username and/or Password are Invalid @\r\n"
	   		+ "Verify the data and try again @\r\n"
	   		+ "The server is under maintenance @\r\n"
	   		+ "Please try again in a few minutes @\r\n"
	   		+ "AUTH SESSION OUT OF SYNC @\r\n"
	   		+ "AUTH TOKEN OBTAINING FAILED @\r\n"
	   		+ "MESSAGE MESSAGE ID MISSING FORMAT @\r\n"
	   		+ "MESSAGE DOES NOT EXIST @\r\n"
	   		+ "MESSAGE NO MESSAGE CREATOR @\r\n"
	   		+ "MEDIA DATA DOES NOT EXIST @\r\n"
	   		+ "MESSAGE DETAIL MESSAGE ID MISSING FORMAT @\r\n"
	   		+ "MESSAGE DETAIL DOES NOT EXIST @\r\n"
	   		+ "MESSAGE DETAIL DELETED @\r\n"
	   		+ "MESSAGE DETAIL DOES NOT EXIST MESSAGE TIME @\r\n"
	   		+ "MY ACCOUNT INVITATION CODE NOT AVAILABLE @\r\n"
	   		+ "MY ACCOUNT INVITATION CODE CANNOT BE EMPTY @\r\n"
	   		+ "VALIDATION OF MY ACCOUNT LOCK SECONDS @\r\n"
	   		+ "ENCRYPT IS NULL @\r\n"
	   		+ "ENCRYPT PRIVATE KEY IS NULL @\r\n"
	   		+ "ENCRYPT PUBLIC KEY IS NULL @\r\n"
	   		+ "ENCRYPT PUBLIC KEY IS NOT NULL @\r\n"
	   		+ "ENCRYPT PUBLIC KEY INVITATION MUST BE NULL @\r\n"
	   		+ "ENCRYPT PROCESS @\r\n"
	   		+ "DECRYPT PROCESS @\r\n"
	   		+ "ENCRYPT AES IS NULL @\r\n"
	   		+ "ENCRYPT AES SECRET KEY IS NULL @\r\n"
	   		+ "ENCRYPT AES SALT IS NULL @\r\n"
	   		+ "ENCRYPT AES CREATION FAILED @\r\n"
	   		+ "DESCRYPT ID PROCESS FAILED @\r\n"
	   		+ "ENCRYPT ID PROCESS FAILED @\r\n"
	   		+ "CONNECTIONLESS MESSAGING @\r\n"
	   		+ "INVALID MESSAGING ACCESS PROTOCOL @\r\n"
	   		+ "ERROR GETTING ONLINE MESSAGING MEMBERS @\r\n"
	   		+ "SESSION MANAGER DISCONNECTED @\r\n"
	   		+ "HEALTH CHECKER PING NO RESPONSE @\r\n"
	   		+ "GENERAL IDS PROVIDER ERROR @\r\n"
	   		+ "IDS PROVIDER DISCONNECTED @\r\n"
	   		+ "IDS PROVIDER UPDATE SHOULD NOT BE INVOKED IN THIS CASE @\r\n"
	   		+ "KEYLOCK ERROR @\r\n"
	   		+ "KEYLOCK UPDATE ERROR @\r\n"
	   		+ "The original message is configured to block forwarding @\r\n"
	   		+ "An Administrator assigned you the Admin Role @\r\n"
	   		+ "An Administrator assigned you the Read-Only Role @\r\n"
	   		+ "An Administrator assigned you the Moderator Role @\r\n"
	   		+ "An Administrator assigned you the Member Role @\r\n"
	   		+ "Emergency Lock @\r\n"
	   		+ "AN ADMINISTRATOR HAS MODIFIED THE GROUP LOCK SETTINGS @\r\n"
	   		+ "AN ADMINISTRATOR HAS MODIFIED THE GENERAL GROUP SETTINGS @\r\n";
	   
	   
	        JAXBContext jaxbContext;
	       
	          jaxbContext = JAXBContext.newInstance(Root.class);
	          Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
	          Root employee = (Root) jaxbUnmarshaller.unmarshal(new StringReader(xmlString));
	        //  System.out.println(employee);
	          //\t\t\t@
	          String[] x = traduccion.split("@");
	          for (int i = 0 ; i < employee.getString().length; i++) {
	        	///
	        	  // System.out.println(employee.getString()[i].string + "\t\t\t@");
	        	 System.out.println("<string name=\"" +employee.getString()[i].name + "\">" + x[i].trim() +"</string>");
	          }


	}

}